### ISSUE TITLE
 wxHexEditor v0.22-v0.24 Linux (Language English [en_GB] is not supported by the system)

### ISSUE THREAD

**Issue by neoh4x0r** [EUA/wxHexEditor#10]
wxHexEditor version: v0.24 (rev 3b3e32d5aa8957a5bda63c8fab056a9f3c42a06e)
Also happens when using wxHexEditor (0.22+repack-2.2) from the debian repository

     Distribution: Debian 
           Version: 8 (debian version: 8.2
 Support Lifecycle: N\A
          Codename: 8 (jessie) 
          Fullname: Debian GNU/Linux 8 (jessie)

       Kernel Name: Linux
    Kernel Release: 3.16.0-4-amd64
    Kernel Version: #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04)

Machine Architecture: x86_64
Error Message:

00:23:30: Cannot set locale to language "English".
00:23:30: locale 'en_GB' cannot be set.
00:23:30: This language is not supported by the system.

-- why is it using en_GB instead of en_US for the English language?
Should there not be a language option for 'English (GB)' / 'English (US)'

**Comment by EUA** [comment]
Yeah confirmed. This is annoying. Will fixed before release.

**Comment by EUA** [comment]
Fixed in 6bfd62117e4c995740e12728951e180ec700e832
