### ISSUE TITLE
Text search not working as expected

### ISSUE THREAD

**Issue by ajcashin** [EUA/wxHexEditor#100]
wxHexEditor 0.24 Beta for Windows 32 bit, Windows 7 professional SP1 64-bit.
I tried searching for a text string (specifically NTFS... (. = space) from the start of a disk, it wasn't found. Placing the search start 100,000 sectors from the start and searching backward, it was found. Before posting this, I tried the same on a file, same result. Searching forward doesn't find anything, searching backwards works fine.
Also, the sector address in the offset column doesn't display correctly (a 500Gb disk with 512 byte sectors). The column was filled with repeated %09I64:03 with no wrapping. So the offset addresses didn't fill the column. A 4Tb disk with 4096 byte sectors also had this problem, but I don't have the disk any more so I can't tell if it was the same string.
Apart from those minor problems, the program was great, I was able to do everything I wanted. The data interpreter feature was very useful. I am posting this as a FYI, I don't need these things to work.

**Comment by EUA** [comment]
I found that "Find" is heavily corrupted. Probably due OpenMP or SSE2 optimizations.
Will analyze it and fix.
Thanks

**Comment by EUA** [comment]
I fixed the bug at trunk.

Will look at offset address issue in Block mode.
Indeed I believe that is Windows dependent problem.
Also I don't have any disk bigger than 250GB.
Well, might better to create  Windows VM under linux with virtual 4TB disk to test the issue.
Thanks.

**Comment by the-r3dacted** [comment]
> Drop your email for sending compiled binary for you.

Can you release this build publicly pls
