### ISSUE TITLE
Modifying one byte modifies next byte

### ISSUE THREAD

**Issue by fenugrec** [EUA/wxHexEditor#101]
Weird :
1) create new file, example random data : 
`00 00 00 00 55 00 00 00 00 00`

2) modify one byte like this, by clicking on the "00" and entering "01" 
`00 00 00 01 55 00 00 00 00 00`

3) Save As... (new file)
4) open that new file :
`00 00 00 01 F5 00 00 00 00 00`

**Comment by EUA** [comment]
This simply not true on my local using latest trunk.
Can you tell your OS for inspection?

**Comment by fenugrec** [comment]
Hi,
I'm not surprised this could be platform-specific. Here's some info -
- arch linux
- git @ 263e19b
- wxgtk3 3.0.3.1
- anything other versions you need to know ?

I can run gdb and inspect things; I just need to know what to look for.

**Comment by EUA** [comment]
I am also use Arch Linux. Weird.

You can inspect about multiple location but not sure where is the problem is...
Keyboard inputs redirected to:
`void HexEditor::OnKeyboardChar( wxKeyEvent& event ) `
But your problem looks like on "Save As" mechanism.
`bool HexEditor::FileSave( wxString savefilename `
both located on HexEditor.cpp

You better to use latest commit and test first.

**Comment by fenugrec** [comment]
AH ! found the problem : I mostly work from the keyboard, and when I save a file I press Alt+F , then A. It appears HexEditor::OnKeyboardChar() only checks for modifiers at the end of the function, so the "F" char is parsed as a hex digit.

I tried moving
```
	if( event.AltDown() || event.ControlDown() ) 
	   event.Skip();
```
to the top of HexEditor::OnKeyboardChar(), but it doesn't work as I thought : for some reason event.AltDown() returns 0 even when pressing "Alt+F" ?

**Comment by EUA** [comment]
Yeah, at least you identified the issue. You also skip character processing by remaining of the function by returning it ;)

**Comment by fenugrec** [comment]
haha totally forgot to add `return` . Thanks!
