### ISSUE TITLE
possible typo : stray ';'

### ISSUE THREAD

**Issue by fenugrec** [EUA/wxHexEditor#102]
The lines around 

https://github.com/EUA/wxHexEditor/blob/27917f36295ebd554cfb44f59b5a7221cffe3494/src/HexDialogs.cpp#L1136

are pretty confusing : the indentation is weird, and it looks like 
`if( ! progress_gauge->Update( percentage) );		// update progress and break on abort`
shouldn't have a semicolon there !

I could submit a PR but wanted to verify the intent of this part of the code.

**Comment by EUA** [comment]
Yup. Fixed.
