### ISSUE TITLE
FreeBSD build?

### ISSUE THREAD

**Issue by Peter2121** [EUA/wxHexEditor#105]
I'm trying to build wxHexEditor (cloned from GitHub) on FreeBSD 11 with codeblocks installed.

The project opens correctly, but trying to build it I get many errors about headers lost:

```
||=== Build: Release in wxHexEditor (compiler: GNU GCC Compiler) ===|
mhash/include/mutils/mincludes.h|34|fatal error: mutils/mhash_config.h: No such file or directory|
mhash/include/mutils/mincludes.h|34|fatal error: mutils/mhash_config.h: No such file or directory|
/usr/home/peter/Programming/wxHexEditor/src/FAL.h|34|fatal error: wx/wx.h: No such file or directory|
||=== Build failed: 3 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|
/usr/home/peter/Programming/wxHexEditor/src/HexEditorApp.h|53|fatal error: wx/app.h: No such file or directory|
||=== Build failed: 4 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|

```
Following your Linux procedure in _COMPILE_, I need to install 

> wxHexEditor library for compilation

It is not clear at all, no such library is available in your GitHub account.
Both wx28-gtk2-2.8.12 and wx30-gtk2-3.0.2 are installed in my system.

**Comment by EUA** [comment]
Hi,
`error: wx/wx.h`
means you don't setup wxGTK properly. Probably you need to install development packages instead of run libs.
"mutils/mhash_config.h" error means you don't compile mhash library first.

Indeed I don't remember how I compile it in FreeBSD.
You might be better using make command after installing wxgtk-devel.

**Comment by Peter2121** [comment]
There is no *-devel packages in FreeBSD, normal library package installs all the necessary files to compile anything.
I have wx.h in /usr/local/include/wx-2.8/wx and in /usr/local/include/wx-3.0/wx, there are many other *.h files in these dirs.
I'll try with make command.

**Comment by EUA** [comment]
Himm, probably your compiler path doesn't include /usr/**local**/include but /usr/include

**Comment by Peter2121** [comment]
So, I added to my environment:
```
LD_LIBRARY_PATH=/usr/local/lib
LIBRARY_PATH=/usr/local/lib
CPATH=/usr/local/include
```
Then I modified in Makefile:
`WXCONFIG ?= wx-config`
to
`WXCONFIG ?= wxgtk2u-2.8-config`

Then I try to build it using gmake.
I got compilation errors like this:
```
src/FAL.cpp:65:12: error: use of undeclared identifier 'DKIOCGETBLOCKSIZE'
        ioctl(FD, DKIOCGETBLOCKSIZE, &block_size);
src/FAL.cpp:85:12: error: use of undeclared identifier 'DKIOCGETBLOCKCOUNT'
        ioctl(FD, DKIOCGETBLOCKCOUNT, &block_count);
src/FAL.cpp:866:13: error: no matching function for call to 'ptrace'
                                        word = ptrace(PTRACE_PEEKTEXT, ProcessID, addr);
src/FAL.cpp:885:50: error: arithmetic on a pointer to void
                        memcpy( buffer, internal_file_buffer.GetData()+from, size );
```

**Comment by EUA** [comment]
Himm. They are the real issues. I have to change some locations to make it compatible for FreeBSD.
I will install FreeBSD VM and try to fix them.
Thanks.

**Comment by Peter2121** [comment]
Thanks for supporting our platform, hope to see wxHexEditor in ports tree one day ;)

**Comment by EUA** [comment]
@Peter2121 I like to support but ... I think FreeBSD has some issues with [KVM/QEMU Xorg](https://forums.freebsd.org/threads/freebsd11-on-qemu-xorg-fails.60824/) VM setups. 
I just download X11 qcow image and installed xorg & gnome3. But xorg doesn't want to work...
Any help?

**Comment by Peter2121** [comment]
As it was mentioned in the forum post, it is really simple to use VirtualBox. There are VB additions that you can install directly from packages on VM, and if you install Oracle VB extensions on the host - even the video acceleration should work correctly on guest VM. I can share a pre-installed VB image if you want.
As I use FreeBSD as OS, I have no experience of using KVM. I know that FreeBSD as guest works fine on VirtualBox and VMware ESXi/Workstation.
As about DE - you should use XFCE or LXDE, that's the most stable DEs on FreeBSD. You can try Lumina too.

**Comment by EUA** [comment]
Installed using [UEFI way](https://forums.freebsd.org/threads/freebsd-xorg-now-works-under-kvm-qemu-no-need-to-compile-using-gcc-anymore.64822/). It's Working now.
Also fixed many things and able to compile right now...
But now wxHexEditor gives segmentation fault at startup.
Probably BSD support will updated this night or next.

**Comment by EUA** [comment]
@Peter2121  I just compiled and got segfault. As I understand segfault not due program because it's before execution of init.
So I decide compile wxWidgets at FreeBSD. Unfortunately, with same result.
When I try to compile & run wxWidgets own samples at samples directory, they also give segmentation error and exit. I don't know what is happening here. I compiled wxWidgets lib for both GTK2 and GTK3 with same result...

**Comment by EUA** [comment]
I don't know when and why this clang love appeared on BSD but the problem is GCC incompatibility.
After switching to clang, it starts working.
You can compile easily with 
`gmake WXCONFIG=wxgtk2-3.0-config`
old **make** command make some error on compilation somehow...
Anyway, It's your turn to make beta testing. :+1:

**Comment by Peter2121** [comment]
It seems that there is a problem of library:
```
$ gmake WXCONFIG=/usr/local/bin/wxgtk2u-3.0-config
c++ src/HexEditorGui.o src/FAL.o src/HexDialogs.o src/HexPanels.o src/HexEditorApp.o src/HexEditor.o src/HexEditorCtrl/HexEditorCtrl.o src/HexEditorCtrl/wxHexCtrl/TagDialogGui.o src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.o src/HexEditorCtrl/wxHexCtrl/Tag.o src/HexEditorCtrl/HexEditorCtrlGui.o src/HexEditorFrame.o -lgomp udis86/libudis86/.libs/libudis86.a mhash/lib/.libs/libmhash.a   `/usr/local/bin/wxgtk2u-3.0-config --libs` `/usr/local/bin/wxgtk2u-3.0-config --libs aui` `/usr/local/bin/wxgtk2u-3.0-config --libs core` -o wxHexEditor
/usr/bin/ld: cannot find -lgomp
```
/usr/local/lib/gcc6/libgomp.so.1.0.0 is present, symlink libgomp.so is present in the same dir
Adding /usr/local/lib/gcc6 to LIBRARY_PATH don't help a lot - there are still OPENMP related errors:
```
src/HexDialogs.o: In function `FindDialog::FindBinaryForward(wxMemoryBuffer, unsigned long, unsigned long, unsigned int,
wxProgressDialog*, wxString&, unsigned long&)':
src/HexDialogs.cpp:(.text+0x5eed): undefined reference to `__kmpc_fork_call'
src/HexDialogs.o: In function `.omp_outlined.':
src/HexDialogs.cpp:(.text+0x7342): undefined reference to `__kmpc_for_static_init_4'
src/HexDialogs.cpp:(.text+0x740f): undefined reference to `__kmpc_for_static_fini'
src/HexDialogs.o: In function `CompareDialog::Compare(wxFileName, wxFileName, bool, int, wxFileName)':
src/HexDialogs.cpp:(.text+0xeb38): undefined reference to `__kmpc_fork_call'
src/HexDialogs.o: In function `.omp_outlined..124':
src/HexDialogs.cpp:(.text+0x11886): undefined reference to `__kmpc_for_static_init_4'
src/HexDialogs.cpp:(.text+0x11b8a): undefined reference to `__kmpc_for_static_fini'
src/HexDialogs.o: In function `ChecksumDialog::CalculateChecksum(FAL&, int)':
src/HexDialogs.cpp:(.text+0x13e34): undefined reference to `__kmpc_fork_call'
src/HexDialogs.o: In function `.omp_outlined..148':
src/HexDialogs.cpp:(.text+0x14a96): undefined reference to `__kmpc_dispatch_init_4u'
src/HexDialogs.cpp:(.text+0x14ac9): undefined reference to `__kmpc_dispatch_next_4u'
src/HexDialogs.cpp:(.text+0x14b0d): undefined reference to `__kmpc_single'
src/HexDialogs.cpp:(.text+0x14b3b): undefined reference to `__kmpc_end_single'
src/HexDialogs.cpp:(.text+0x14b48): undefined reference to `__kmpc_barrier'
src/HexDialogs.cpp:(.text+0x14b67): undefined reference to `__kmpc_end_single'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Peter2121** [comment]
OK, I've got it.
One need to install openmp package, the library from gcc6 does not work correctly here.
I can start wxHexEditor and open files, but it crashes trying to create new file:
`Floating point exception (core dumped)`

**Comment by Peter2121** [comment]
gmake install is failed:
```
$ gmake 
install -D -m 755 wxHexEditor //usr/local/bin/wxHexEditor
install: target directory `//usr/local/bin/wxHexEditor' does not exist
```
(I changed prefix in Makefile, without such modification it tries /usr/bin/wxHexEditor and failed the same way)

**Comment by EUA** [comment]
I removed the "-D" and it looks working proper now.
Please try again.

gcc issue is true at FreeBSD. Probably due libs... I think it's nothing to do for me.
I just use clang.

**Comment by EUA** [comment]
Tested with FreeBSD12 and working with instructions.
