### ISSUE TITLE
Segmentation fault (core dumped) probably caused by Oracle Java version 7 on Ubunutu 16 

### ISSUE THREAD

**Issue by skanwwal** [EUA/wxHexEditor#107]
Hi, 

I installed oracle java version 7 on ubuntu 16.4 64 bit ASUS OS. Version 7 is required for matlab 2015b on ubunut linux system. Howver, it keeps multiple errors and do not run commands successfully in the terminal especially those application/commands involving java. I am attaching here error from the system. Would really appreciate if someone can help to fix this error. 

![whatsapp image 2018-04-18 at 5 20 06 pm](https://user-images.githubusercontent.com/33715874/38923297-cd6e1de8-432c-11e8-8829-c58f9248cac0.jpeg)

![whatsapp image 2018-04-18 at 3 56 54 pm](https://user-images.githubusercontent.com/33715874/38922935-fa9a259c-432b-11e8-8fcc-23b9912cf948.jpeg)

![whatsapp image 2018-04-18 at 3 57 02 pm](https://user-images.githubusercontent.com/33715874/38922951-0141820a-432c-11e8-9361-96d1e220f4cf.jpeg)

**Comment by EUA** [comment]
Hi, this project does not use ANY java libraries.
