### ISSUE TITLE
Compare files dialog should try to pre-fill with what I have already open

### ISSUE THREAD

**Issue by mirh** [EUA/wxHexEditor#109]

**Comment by EUA** [comment]
Compare files just compare 2 files for changes.
Not make advanced logical differentiation. I mean does not search a file under another file. If you ask for this, it's not a planned feature yet and I don't work on it soon.

**Comment by mirh** [comment]
I'm asking that if I have two files opened in the normal view
Their paths should automatically fill the "compare files" dialog when I select it.

**Comment by EUA** [comment]
Well, all you need to know is, I tried but can't make it stabilize. At least for Gnome.

Problem is : wxFilePickerCtrl class does not work properly. SetPath sets the path but wxFilePickerCtrl looks like not set, appears as (None). So, I think wxFilePickerCtrl is not mature enough. I found some improvements to this class (to wx3.0 -> wx3.1.3) but it's not enough.

Also If I was successful on it, program will open same files with another hex editor tab for comparison.
For proper implementation, we need to use already opened 2 files... etc.

After thinking the gain and the problems that I need to solve and their complexity.
I decide not to implement this. I paid too much effort to this already.
Sorry!
