### ISSUE TITLE
Hotkeys for tags

### ISSUE THREAD

**Issue by procedural** [EUA/wxHexEditor#11]
http://wiki.wxhexeditor.org/index.php5/TAGs

Is there any hotkeys for these?

**Comment by EUA** [comment]
I can add if there is none :+1:

**Comment by procedural** [comment]
@EUA it would be a huge time saver for me!

**Comment by EUA** [comment]
What shortcuts do you like? CTRL+Q look good for Quick tag and CTRL+T for normal tag sounds good to me.
Hımm. CTRL+Q is also for Quit for many programs.

CTRL+T for Quick Tag
CTRL+SHIFT+T for Normal Tag looks better.

**Comment by EUA** [comment]
Added. But TAG creation looks not work proper for now. Will solve that also.
