### ISSUE TITLE
Improvement: locations of tags

### ISSUE THREAD

**Issue by jumpjack** [EUA/wxHexEditor#116]
It would be nice if search result pane could show offsets of selected tag.

By the way: I spent hours to find an hex editor capable of higlighting "sequences of bytes", because in other editors (all payware) they are called: structures, templates, patterns, or whatever.

**Comment by EUA** [comment]
Hi.
I don't understand this request.
Search result panel is already shows offsets.
What do you mean with "offsets of selected tag"?
You can't "select tag" in wxHexEditor.
Clicking that tag/search result just move cursor to that tag, nothing more.

**Comment by EUA** [comment]
Search results now shows start-end offset and the length.
Now (trunk) also support converting search results to tag...
