### ISSUE TITLE
Tag exporting not properly implemented

### ISSUE THREAD

**Issue by jumpjack** [EUA/wxHexEditor#117]
Tag import/export is very useful... but only if DEFINITION are imported/exported, not offsets, else loading TAGs from a different file will result in improper highlighting of meaningless bytes.
It could be implemented an "offset import/export" function (although I can't see its task)

**Comment by EUA** [comment]
I think this is duplicate of #84, adding offset to import/export.

If you mean that, program need to scan file and understand it's structure, than it's count as same as #20.
So closing this...
