### ISSUE TITLE
v0.23: Tag import is broken on Windows

### ISSUE THREAD

**Issue by procedural** [EUA/wxHexEditor#12]
v0.22a imports and updates tags fine.

v0.23 imports tags too, but then if you try to create a new tag or delete one it won't update the hex display window as if you did nothing.

wxHexEditor versions were downloaded from sourceforge:
http://sourceforge.net/projects/wxhexeditor/files/wxHexEditor/

**Comment by EUA** [comment]
I believe your problem is resolved with f859212f249bfa77b618965f952934065f5d3e73
Tested under linux and works proper now. It won't be different for Windows.

**Comment by procedural** [comment]
@EUA thanks, it might be it! I guess now I have to wait for v0.24 for Windows binaries... :)
