### ISSUE TITLE
change AM_GNU_GETTEXT to AM_GLIB_GNU_GETTEXT

### ISSUE THREAD

**Issue by admzzz** [EUA/wxHexEditor#120]
otherwise one gets error: `autoreconf: configure.ac: not using Gettext` and compilation fails

**Comment by EUA** [comment]
autoreconf used in udis86 and mhash libraries... But I can't find which file I need to change...
Anyway, udis86 is deprecated.
Capstone Disassembler in my horizon.

**Comment by EUA** [comment]
I can't find AM_GNU_GETTEXT
