### ISSUE TITLE
Go to Offset doesn't update cursor on screen

### ISSUE THREAD

**Issue by AltoRetrato** [EUA/wxHexEditor#121]
Hi, there!

I'm running wxHexEditor-v0.24-Win64 on Windows 10.

When I press [Ctrl]+[G] or use "Edit > Go to Offset", the screen scrolls to the location I've chosen, the "Cursor Offset" and "Cursor Value" in the status bar are correct, but the selection cursor is in the wrong position. If I repeat the "Go to Offset" jump (i.e., jump to the same address "From beginning"), then the cursor appears in the right position.

Steps to reproduce the problem:

- Open a file (cursor will be in the offset 0)
- Press [Ctrl]+[G]
- Select "Type of branch": "From beginning"
- Set "Offset" to 1, click "Go!"
- Expected result: cursor at offset 1; actual result: cursor at the same position (offset 0)
- Press [Ctrl]+[G] again, click "Go!"
- Now cursor will appear in the right position (offset 1)
- Press [Ctrl]+[G] again, set offset to 0, click "Go!"
- Expected result: cursor at offset 0; actual result: cursor at the same position (offset 1)
- Press [Ctrl]+[G] again, click "Go!"
- Now cursor will appear in the right position (offset 0)

**Comment by wonson** [comment]
I have the same problem as well. my search need to scroll, so it becomes more difficult to find.
Thanks for the "ctrl+g twice" method, haha

it seems that the cursor already goes to the position in background, but not updated in visual.
when do it twice, the visual finally updated?

**Comment by AltoRetrato** [comment]
That's what seems to happen.

But to tell the truth, there are just too many bugs in this editor, I just moved on to others...

**Comment by EUA** [comment]
Hi.
Indeed I don't really debug under windows. Looks working OK under Linux.  Will look this under VM.
