### ISSUE TITLE
Show ASCII char names

### ISSUE THREAD

**Issue by rdiez** [EUA/wxHexEditor#127]
First of all, many thanks for wxHexEditor.

Would it be possible for the "data interpreter" panel to show the ASCII char name of the current byte?

You will find a list of ASCII char names here:

https://github.com/rdiez/Tools/blob/master/AnnotateWithTimestamps/AnnotateWithTimestamps.pl

Just search for "asciiCharNames" in that file.

**Comment by EUA** [comment]
Hello. Thank you for your compliments.
This could be done. But what that panel show other ASCII or non-ascii characters?
"NONE" or might character description is OK.

This table looks good.
https://www.ascii-code.com/

**Comment by rdiez** [comment]
For the script I mentioned I took the character names from the Wikipedia:

https://en.wikipedia.org/wiki/ASCII

For normal (printable) ASCII characters, I would just display the character itself. For example:
ASCII: K

For non-printable characters:
ASCII: <LF>

You could add further codepages like this:
Windows-1252: Ž

But that is a luxury feature. Most of the time, when looking in a hex editor, and the character is not printable, I normally need the names of the ASCII control codes under 32. For example, I can never remember which is one CR and which one LF.

**Comment by EUA** [comment]
I think this is enough for what you need.
```
wxString DataInterpreter::AsciiSymbol( unsigned char ch ){
    static wxString AsciiTable[]={"NUL","SOH","STX","ETX","EOT","ENQ","ACK","BEL","BS","HT","LF","VT",
								"FF","CR","SO","SI","DLE","DC1","DC2","DC3","DC4","NAK","SYN","ETB",
								"CAN","EM","SUB","ESC","FS","GS","RS","US","SP"};//32 SP means SPACE
	if( ch <= 32 )
		return AsciiTable[ch];
	else if( ch > 32 && ch < 127 )
		return wxString((char)ch);
	else if( ch == 127 )
		return wxString("DEL");
	return wxEmptyString;
	}
```

Does it better to use full description of character instead of symbol?

**Comment by rdiez** [comment]
I think your solution is good enough. Thanks a lot!
