### ISSUE TITLE
AMD64 Not supported & old url still being used

### ISSUE THREAD

**Issue by awsdert** [EUA/wxHexEditor#128]
I'm on linux mint x64, I compiled a simple binary to get an understanding of how to use cpu instructions so that I can write my own compiler with an MIT license but when looking at the result in wxHexEditor it only provides INTEL & AT&T as options.

Also when I clicked the report bug option in the help menu it brought me to https://sourceforge.net/p/wxhexeditor/bugs/

**Comment by awsdert** [comment]
If you need a reference I found this:
http://ref.x86asm.net/coder64.html

**Comment by frhun** [comment]
Intel and AT&T refer to the assembler syntax, not the instruction set.
So it has nothing to do with instruction set support.

**Comment by EUA** [comment]
Hello,
At first old URL changed in GitHub long before.
And for disassembler, I use udis86 library. I thought it support AMD64 instruction too, doesn't it?
Okay, anyway.
In future wanted to switch to CapStone engine.
Which is supervisor to udis86 and supports : Arm, Arm64 (Armv8), BPF, Ethereum Virtual Machine, M68K, M680X, Mips, MOS65XX, PowerPC, RISCV, Sparc, SystemZ, TMS320C64X, Web Assembly, XCore & X86 which includes X86_64 too.

I think it's enough for your needs. :)

**Comment by awsdert** [comment]
Sorry I'm rather late to respond, been playing games and whatnot, also forgot I started this thread (only found it cause I'm reducing my bookmarks by locating thread based ones and just switching for a single thread search linked to my relative profiles). Anyways thanks very much I'll try it out when I get a chance (in middle of a separate but related project where I analyse expressions built from integers, floating point numbers, character literals, strings and calculate the result) which will be part of a portable compiler I'm trying to make
