### ISSUE TITLE
Hex and Text controls shows different data when using multi-byte encoding

### ISSUE THREAD

**Issue by Extravert-ir** [EUA/wxHexEditor#13]
When opening file with multi-byte encoding and then do some scrolling, Hex and Text controls begin to show different data.
See screenshot: there are mostly zeros on line with offset 14442 but text shown in Text window is completely different
![screenshot from 2015-11-08 09-56-35](https://cloud.githubusercontent.com/assets/961957/11019236/68fe37a8-8600-11e5-8c06-b4656b811fa0.png)

**Comment by EUA** [comment]
Multi-byte encoding is not finalized and might have lots of bugs.
I try to fix most of issues related with it. But cannot test many of encoding due lack of file for inspect.

I will inspect this behavior.
Can you tell that take this shot in which encoding setting?

**Comment by Extravert-ir** [comment]
It is UTF-16LE

**Comment by EUA** [comment]
I don't have such a corruption at my local.
Can you upload a small sample file for this issue or could verify that error is fixed with latest git.
Thanks.

**Comment by Extravert-ir** [comment]
Yes, it works fine with latest commit. Well done!
Compiled with libwxgtk3.0 (2.x not tested)
