### ISSUE TITLE
Crashes when file is updated

### ISSUE THREAD

**Issue by awsdert** [EUA/wxHexEditor#130]
a reminder I'm on linux x64 mint, I compile an elf, open it with wxHexEditor then after checking what I want to check and modifying my code I then recompile, I close the tab and try to re-open the file, at this point it crashes or more specifically just shuts down on me, I've tried closing the tab before re-compiling at same issue, I've tried via the close button and middle click and wxHexEditor still shuts down on me

**Comment by EUA** [comment]
Hi,
Can you try this again with git trunk version?

**Comment by awsdert** [comment]
Hi sorry for late reply, I'll try as soon as I find the project (got a tad too many which I've yet to complete 😅

**Comment by awsdert** [comment]
I recently changed OS so the final result might be different but I won't know that just yet, I tried to compile wxHexEditor via running make but I got a bunch of errors, the 1st being a lack of wx/wxprec.h so I installed both the gtk2 and gtk3 based versions so should be no issues there. I'll show the string of errors that appeared from that 1st error:
[code]
rc/HexEditorGui.cpp:8:10: fatal error: wx/wxprec.h: No such file or directory
    8 | #include "wx/wxprec.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:59: src/HexEditorGui.o] Error 1
[zxuiji@zxuiji-manjaro wxHexEditor]$ make
g++ -c    `wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -Wall -O2 -fopenmp src/HexEditorGui.cpp -o src/HexEditorGui.o
g++ -c    `wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -Wall -O2 -fopenmp src/FAL.cpp -o src/FAL.o
src/FAL.cpp: In member function ‘bool FAL::Apply()’:
src/FAL.cpp:630:17: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
  630 |       while (wr < rd_size) {
      |              ~~~^~~~~~~~~
src/FAL.cpp:641:14: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
  641 |       success*=true;
      |       ~~~~~~~^~~~~~
src/FAL.cpp: In member function ‘wxFileOffset FAL::Length(int)’:
src/FAL.cpp:786:24: warning: comparison of integer expressions of different signedness: ‘unsigned int’ and ‘int’ [-Wsign-compare]
  786 |  for( unsigned i=0 ; i < PatchIndice; i++ )
      |                      ~~^~~~~~~~~~~~~
g++ -c    `wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -Wall -O2 -fopenmp src/HexDialogs.cpp -o src/HexDialogs.o
In file included from src/HexEditorCtrl/HexEditorCtrlGui.h:28,
                 from src/HexEditorCtrl/HexEditorCtrl.h:43,
                 from src/HexPanels.h:28,
                 from src/HexEditorFrame.h:32,
                 from src/HexPanels.h:27,
                 from src/HexEditor.h:37,
                 from src/HexDialogs.h:28,
                 from src/HexDialogs.cpp:25:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h: In constructor ‘wxHexOffsetCtrl::wxHexOffsetCtrl(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int, const wxValidator&)’:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:282:4: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  282 |    if( offset_mode=='s' ) // No force to sector mode at startup.
      |    ^~
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:285:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  285 |     offset_position=0;
      |     ^~~~~~~~~~~~~~~
src/HexDialogs.cpp: In function ‘bool HexVerifyAndPrepare(wxString&, wxString, wxWindow*)’:
src/HexDialogs.cpp:71:28: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
   71 |    while( hexval.find(' ') != -1 )
      |           ~~~~~~~~~~~~~~~~~^~~~~
src/HexDialogs.cpp: In member function ‘void FindDialog::FindSomeBytes()’:
src/HexDialogs.cpp:493:37: warning: comparison of integer expressions of different signedness: ‘uint64_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]
  493 |    backward_offset = current_offset < search_step ? 0 : current_offset-search_step;
      |                      ~~~~~~~~~~~~~~~^~~~~~~~~~~~~
src/HexDialogs.cpp: In member function ‘uint64_t FindDialog::FindBinaryForward(wxMemoryBuffer, uint64_t, uint64_t, unsigned int, wxProgressDialog*, wxString&, uint64_t&)’:
src/HexDialogs.cpp:993:6: warning: suggest parentheses around operand of ‘!’ or change ‘&’ to ‘&&’ or ‘!’ to ‘~’ [-Wparentheses]
  993 |  if (! options & SEARCH_FINDALL)
      |      ^~~~~~~~~
src/HexDialogs.cpp:812:7: warning: unused variable ‘first_run’ [-Wunused-variable]
  812 |  bool first_run=true;
      |       ^~~~~~~~~
src/HexDialogs.cpp:836:11: warning: unused variable ‘read_speed’ [-Wunused-variable]
  836 |  unsigned read_speed=0,percentage=0;
      |           ^~~~~~~~~~
src/HexDialogs.cpp: In member function ‘uint64_t FindDialog::FindBinaryBackward(wxMemoryBuffer, uint64_t, uint64_t, unsigned int, wxProgressDialog*, wxString&, uint64_t&)’:
src/HexDialogs.cpp:1134:5: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wdangling-else]
 1134 |   if( progress_gauge != NULL)
      |     ^
src/HexDialogs.cpp:1022:7: warning: unused variable ‘first_search’ [-Wunused-variable]
 1022 |  bool first_search=true;
      |       ^~~~~~~~~~~~
src/HexDialogs.cpp:1045:11: warning: unused variable ‘read_speed_offset’ [-Wunused-variable]
 1045 |  uint64_t read_speed_offset=0,processfootprint=0;
      |           ^~~~~~~~~~~~~~~~~
src/HexDialogs.cpp: In member function ‘int FindDialog::SearchAtBuffer(char*, int, char*, int, unsigned int, std::vector<int>*)’:
src/HexDialogs.cpp:24:16: warning: overflow in conversion from ‘long long unsigned int’ to ‘int’ changes value from ‘18446744073709551615’ to ‘-1’ [-Woverflow]
   24 | #define NANINT 0xFFFFFFFFFFFFFFFFLL
      |                ^~~~~~~~~~~~~~~~~~~~
src/HexDialogs.cpp:1684:9: note: in expansion of macro ‘NANINT’
 1684 |  return NANINT;
      |         ^~~~~~
src/HexDialogs.cpp: In member function ‘virtual void ChecksumDialog::EventHandler(wxCommandEvent&)’:
src/HexDialogs.cpp:2746:11: warning: deleting object of polymorphic class type ‘FAL’ which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
 2746 |    delete F;
      |           ^
g++ -c    `wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -Wall -O2 -fopenmp src/HexPanels.cpp -o src/HexPanels.o
In file included from src/HexEditorCtrl/HexEditorCtrlGui.h:28,
                 from src/HexEditorCtrl/HexEditorCtrl.h:43,
                 from src/HexPanels.h:28,
                 from src/HexEditor.h:37,
                 from src/HexEditorFrame.h:29,
                 from src/HexPanels.cpp:24:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h: In constructor ‘wxHexOffsetCtrl::wxHexOffsetCtrl(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int, const wxValidator&)’:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:282:4: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  282 |    if( offset_mode=='s' ) // No force to sector mode at startup.
      |    ^~
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:285:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  285 |     offset_position=0;
      |     ^~~~~~~~~~~~~~~
In file included from src/HexEditorFrame.h:33,
                 from src/HexPanels.cpp:24:
src/../resources/wxhex.xpm: At global scope:
src/../resources/wxhex.xpm:2:21: warning: ‘wxhex_xpm’ defined but not used [-Wunused-variable]
    2 | static const char * wxhex_xpm[] = {
      |                     ^~~~~~~~~
g++ -c    `wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -Wall -O2 -fopenmp src/HexEditorApp.cpp -o src/HexEditorApp.o
In file included from src/HexEditorCtrl/HexEditorCtrlGui.h:28,
                 from src/HexEditorCtrl/HexEditorCtrl.h:43,
                 from src/HexPanels.h:28,
                 from src/HexEditor.h:37,
                 from src/HexEditorFrame.h:29,
                 from src/HexEditorApp.h:54,
                 from src/HexEditorApp.cpp:41:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h: In constructor ‘wxHexOffsetCtrl::wxHexOffsetCtrl(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int, const wxValidator&)’:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:282:4: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  282 |    if( offset_mode=='s' ) // No force to sector mode at startup.
      |    ^~
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:285:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  285 |     offset_position=0;
      |     ^~~~~~~~~~~~~~~
In file included from src/HexEditorFrame.h:33,
                 from src/HexEditorApp.h:54,
                 from src/HexEditorApp.cpp:41:
src/../resources/wxhex.xpm: At global scope:
src/../resources/wxhex.xpm:2:21: warning: ‘wxhex_xpm’ defined but not used [-Wunused-variable]
    2 | static const char * wxhex_xpm[] = {
      |                     ^~~~~~~~~
g++ -c    `wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -Wall -O2 -fopenmp src/HexEditor.cpp -o src/HexEditor.o
src/HexEditor.cpp:305:5: warning: multi-line comment [-Wcomment]
  305 |     //std::cout << "Addr :" << addr << " - " << mymeminfo.RegionSize << "   \t State: " << \
      |     ^
In file included from src/HexEditorCtrl/HexEditorCtrlGui.h:28,
                 from src/HexEditorCtrl/HexEditorCtrl.h:43,
                 from src/HexDialogs.h:30,
                 from src/HexEditorFrame.h:31,
                 from src/HexPanels.h:27,
                 from src/HexEditor.h:37,
                 from src/HexEditor.cpp:25:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h: In constructor ‘wxHexOffsetCtrl::wxHexOffsetCtrl(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int, const wxValidator&)’:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:282:4: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  282 |    if( offset_mode=='s' ) // No force to sector mode at startup.
      |    ^~
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:285:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  285 |     offset_position=0;
      |     ^~~~~~~~~~~~~~~
src/HexEditor.cpp: In member function ‘bool HexEditor::FileClose(bool)’:
src/HexEditor.cpp:547:10: warning: deleting object of polymorphic class type ‘FAL’ which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
  547 |   delete myfile;
      |          ^~~~~~
In file included from src/HexEditorFrame.h:33,
                 from src/HexPanels.h:27,
                 from src/HexEditor.h:37,
                 from src/HexEditor.cpp:25:
src/../resources/wxhex.xpm: At global scope:
src/../resources/wxhex.xpm:2:21: warning: ‘wxhex_xpm’ defined but not used [-Wunused-variable]
    2 | static const char * wxhex_xpm[] = {
      |                     ^~~~~~~~~
g++ -c    `wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -Wall -O2 -fopenmp src/HexEditorCtrl/HexEditorCtrl.cpp -o src/HexEditorCtrl/HexEditorCtrl.o
In file included from src/HexEditorCtrl/HexEditorCtrlGui.h:28,
                 from src/HexEditorCtrl/HexEditorCtrl.h:43,
                 from src/HexEditorCtrl/HexEditorCtrl.cpp:24:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h: In constructor ‘wxHexOffsetCtrl::wxHexOffsetCtrl(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int, const wxValidator&)’:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:282:4: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  282 |    if( offset_mode=='s' ) // No force to sector mode at startup.
      |    ^~
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:285:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  285 |     offset_position=0;
      |     ^~~~~~~~~~~~~~~
g++ -c    `wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -Wall -O2 -fopenmp src/HexEditorCtrl/wxHexCtrl/TagDialogGui.cpp -o src/HexEditorCtrl/wxHexCtrl/TagDialogGui.o
g++ -c    `wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -Wall -O2 -fopenmp src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp -o src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.o
In file included from src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp:25:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h: In constructor ‘wxHexOffsetCtrl::wxHexOffsetCtrl(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int, const wxValidator&)’:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:282:4: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  282 |    if( offset_mode=='s' ) // No force to sector mode at startup.
      |    ^~
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:285:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  285 |     offset_position=0;
      |     ^~~~~~~~~~~~~~~
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp: In member function ‘wxDC* wxHexCtrl::UpdateDC(wxDC*)’:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp:586:10: warning: unused variable ‘cc’ [-Wunused-variable]
  586 |      int cc=col[chrC];
      |          ^~
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp:601:10: warning: unused variable ‘cc’ [-Wunused-variable]
  601 |      int cc=col[chrC];
      |          ^~
g++ -c    `wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -Wall -O2 -fopenmp src/HexEditorCtrl/wxHexCtrl/Tag.cpp -o src/HexEditorCtrl/wxHexCtrl/Tag.o
In file included from src/HexEditorCtrl/wxHexCtrl/Tag.cpp:25:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h: In constructor ‘wxHexOffsetCtrl::wxHexOffsetCtrl(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int, const wxValidator&)’:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:282:4: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  282 |    if( offset_mode=='s' ) // No force to sector mode at startup.
      |    ^~
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:285:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  285 |     offset_position=0;
      |     ^~~~~~~~~~~~~~~
g++ -c    `wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -Wall -O2 -fopenmp src/HexEditorCtrl/HexEditorCtrlGui.cpp -o src/HexEditorCtrl/HexEditorCtrlGui.o
In file included from src/HexEditorCtrl/HexEditorCtrlGui.cpp:18:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h: In constructor ‘wxHexOffsetCtrl::wxHexOffsetCtrl(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int, const wxValidator&)’:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:282:4: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  282 |    if( offset_mode=='s' ) // No force to sector mode at startup.
      |    ^~
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:285:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  285 |     offset_position=0;
      |     ^~~~~~~~~~~~~~~
g++ -c    `wx-config --cxxflags` -Iudis86 -Imhash/include -MMD -Wall -O2 -fopenmp src/HexEditorFrame.cpp -o src/HexEditorFrame.o
In file included from src/HexEditorCtrl/HexEditorCtrlGui.h:28,
                 from src/HexEditorCtrl/HexEditorCtrl.h:43,
                 from src/HexPanels.h:28,
                 from src/HexEditor.h:37,
                 from src/HexEditorFrame.h:29,
                 from src/HexEditorFrame.cpp:24:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h: In constructor ‘wxHexOffsetCtrl::wxHexOffsetCtrl(wxWindow*, wxWindowID, const wxString&, const wxPoint&, const wxSize&, long int, const wxValidator&)’:
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:282:4: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  282 |    if( offset_mode=='s' ) // No force to sector mode at startup.
      |    ^~
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.h:285:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  285 |     offset_position=0;
      |     ^~~~~~~~~~~~~~~
src/HexEditorFrame.cpp: In member function ‘virtual void HexEditorFrame::OnMenuEvent(wxCommandEvent&)’:
src/HexEditorFrame.cpp:588:72: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
  588 |  else if( event.GetId() >= MyFileHistory->GetBaseId() && event.GetId() <= MyFileHistory->GetBaseId()+MyFileHistory->GetCount()-1){
      |                                                          ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/HexEditorFrame.cpp: In member function ‘virtual wxConnectionBase* IPCServer::OnAcceptConnection(const wxString&)’:
src/HexEditorFrame.cpp:1274:1: warning: no return statement in function returning non-void [-Wreturn-type]
 1274 | }
      | ^
In file included from src/HexEditorGui.h:17,
                 from src/HexEditorFrame.h:28,
                 from src/HexEditorFrame.cpp:24:
/usr/include/wx-3.0/wx/menu.h: In member function ‘virtual void HexEditorFrame::OnUpdateUI(wxUpdateUIEvent&)’:
/usr/include/wx-3.0/wx/menu.h:67:82: warning: ‘nm’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   67 |         return DoAppend(wxMenuItem::New((wxMenu *)this, itemid, text, help, kind));
      |                                                                                  ^
src/HexEditorFrame.cpp:921:11: note: ‘nm’ was declared here
  921 |   wxMenu *nm;
      |           ^~
g++   src/HexEditorGui.o src/FAL.o src/HexDialogs.o src/HexPanels.o src/HexEditorApp.o src/HexEditor.o src/HexEditorCtrl/HexEditorCtrl.o src/HexEditorCtrl/wxHexCtrl/TagDialogGui.o src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.o src/HexEditorCtrl/wxHexCtrl/Tag.o src/HexEditorCtrl/HexEditorCtrlGui.o src/HexEditorFrame.o udis86/libudis86/.libs/libudis86.a mhash/lib/.libs/libmhash.a -lgomp `wx-config --libs` `wx-config --libs aui` `wx-config --libs core`  -o wxHexEditor
[/code]
If any of them are something you can fix then do so 1st before I continue cause user end should not see any such errors or warnings, I myself always clear out compiler warnings and errors before uploading any of my code to github if I can

**Comment by EUA** [comment]
This is wxWidgets is not installed/found error.
But you installed wxgtk right?
Than your wx-config file name is something different thatn wx-config.
Test that `wx-config` command probably doesn't return anything on your system.
I don't know the wx-config tool file name on your setup.
write wx-c and press tab for auto-completion. This might give you idea.

If it's wx-config-gtk3 in your system, than try with `make WXCONFIG=wx-config-gtk3`
This probably solve your problem.

**Comment by awsdert** [comment]
whoops, once again got busy and forgot, I'll give it a try when I get back

**Comment by awsdert** [comment]
Finally got round to actually trying it, at some point since my comment with the log I had to reinstall my system and by the time I reinstalled wxHexEditor (tonight) manjaro software manager had been improved to build stuff from AUR, it installed wxgtk or whatever for me, I tried repeating the steps I gave but no issues cropped up this time so I'm guessing either you inadvertently fixed the cause in the backend or the software manager is better suited to building AUR stuff than bauh
