### ISSUE TITLE
Bypass read permissions without root password

### ISSUE THREAD

**Issue by timebrain** [EUA/wxHexEditor#135]
It is possible to open a file with wxHexEditor even if the user does not have read permission on the file.

OS: Linux Debian 10
Kernel: Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19)
Version: wxHexEditor 0.23 Beta for Linux (0.23+repack-3 amd64)

Steps to reproduce the bug:

1. In Xfce4 desktop, open terminal as restricted user.

2. Walk to directory containig secret-file which user does not have read permission for.

3. wxHexEditor secret-file

4. wxHexEditor opens its main window and a pop window saying:
   "File is not readable by permissions.
    Please change file permissons or run this program with root privileges.
    You can also try to own the file temporarily (requires root's password.)
    Do you want to own the file?"
![wxHexEditorOwnFile](https://user-images.githubusercontent.com/16455968/62006735-f9e5f300-b144-11e9-9010-dcf8b8163a84.png)

5. Click button [OK].

6. Without entering root password, secret-file is opened into wxHexEditor in read-only mode.

7. Save a copy of secret-file anywhere and proceed spying on its content.

**Comment by timebrain** [comment]
The issue seems to be specific to Debian 10.
Same version of wxHexEditor in Debian9 does not bypass read permissions.

**Comment by timebrain** [comment]
Case solved: The root password was saved in my keyring.
So not a security issue. Sorry for the alarm.

**Comment by frhun** [comment]
please close the issue when it's solved
