### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by meustrus** [EUA/wxHexEditor#136]
This repository is missing a LICENSE file. [The Sourceforge page](https://sourceforge.net/projects/wxhexeditor/)* says the license is GPLv2, as do the code files, but it would be a good idea to put a copy of [that license](https://github.com/EUA/wxHexEditor/blob/master/docs/GPL.txt) in a `LICENSE` file at the root of this repository. Besides making it more obvious to humans, Github should see this and add a license tab to the repository webpage as well.

\* What is the history of being on Sourceforge *and* Github? It looks like the active development is here, but https://www.wxhexeditor.org/ has a Sourceforge link at the bottom of every page.

**Comment by frhun** [comment]
He said somewhere (on his sourceforge profile i think) that he is abandoning sourceforge, so this is probably the "active" repository.

**Comment by frhun** [comment]
Also the license is here: https://github.com/EUA/wxHexEditor/blob/master/docs/GPL.txt

but i agree that it would be better to put it in the LICENSE file.

**Comment by EUA** [comment]
Done
