### ISSUE TITLE
Flathub Package ready

### ISSUE THREAD

**Issue by frhun** [EUA/wxHexEditor#140]
I have created the [necessary metadata for a Flatpak package](https://github.com/frhun/org.wxhexeditor.wxHexEditor).
It just needs to be submitted to Flathub as per the guidelines [here](https://github.com/flathub/flathub/wiki/App-Submission#how-to-submit-an-app).

I would do it myself but the Flathub people prefer (for obvious Reasons) that the current maintainer submits.
If you don't want the hassle you could just ask them to also give me write access to the metadata-repo, and i will handle the flatpak Runtime updating and permission problems.

**Comment by frhun** [comment]
As i thought it was unlikely you (EUA) respond in the near future, and someone over in the IRC said it is normal for the creator to just request access after the fact in cases like this. I created a PR myself https://github.com/flathub/flathub/pull/1144.

**Comment by frhun** [comment]
Now here: https://github.com/flathub/org.wxhexeditor.wxHexEditor

**Comment by EUA** [comment]
Thank you.
