### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by olcc** [EUA/wxHexEditor#146]
Hello,

Search does not work. 

- Say I want to search for the hexadecimal bytes "76 A6": I hit CTRL+F, select "Hexadecimal", and type "76A6" => The search brings me to a place where the bytes are not there. This is a bug.

- Say I want to search for the text "DER": I hit CTRL+F, select "Text" and type "DER" => The search does not find anything (while I can see "DER" in the text view). This is a bug

Olivier (wxHexEditor 0.24 on Debian Linux)

**Comment by EUA** [comment]
Hi, Can you retry with Git version? Thanks.

**Comment by EUA** [comment]
I previously fixed this before (#100) but found that hex search has defected due compiler error at
`while( hexval.find(' ')>= 0 )`
somehow.
Anyway, now checked and looks work proper.
