### ISSUE TITLE
Writing a byte to a block device writes it to the following block

### ISSUE THREAD

**Issue by PartialVolume** [EUA/wxHexEditor#149]
I'm using the open a device feature of wxhexeditor to view the contents of a disc device. I'm also selecting the direct IO option where data gets immediately written to disc.

So first I wipe the drive so it contains all zeros, then use wxHexEditor to write a value, say 0xFF into a block, and save it. Then exit wxHexEditor and restart it and look at the location the 0xFF is at. It will not be in the offset I wrote it to, but offset by +512 bytes.

The image below explains it. As I type the FF at offset 0 it also appears at offset 512, as I continue typing I place a second 'FF' at offset 2, the FF at offset 512 changes to 0 and FF appears at 513. If you then reload the file there will be only the one FF at offset 513.

I'm editing a 80MB Maxtor IDE drive attached via a USB adapter however this has been tested on a WD500GB drive on ESATA with the same result. I'm using the 0.23 version of wxhexeditor on KDE Neon (based on Ubuntu 18.04LTS). I haven't compiled from source yet to see if it's present in the master.

![wxhexeditor direct write location wrong bug-appended](https://user-images.githubusercontent.com/22084881/68850973-e7300380-06cc-11ea-83f6-2e303aa657b0.png)

**Comment by EUA** [comment]
Hi. Looks like this is not valid for last github trunk version.
Please compile from latest trunk.

**Comment by PartialVolume** [comment]
Will do, I'm having a problem compiling this on KDE Neon (Ubuntu 18.04LTS). It fails with `make: *** No rule to make target '-lgomp', needed by 'src/HexEditorGui.o'. Stop.` 

And if I take at look at libomp and try to install libomb-dev it wants to downgrade from 8 to 5 ..

> The following information may help to resolve the situation:
The following packages have unmet dependencies.
 libomp-dev : Depends: libomp5 (= 5.0.1-1)
E: Unable to correct problems, you have held broken packages.

Once I get that that sorted I'll let you know whether there is still a problem.

**Comment by PartialVolume** [comment]
For some reason libomp-8 was installed but there doesn't appear to be a libomp-8-dev in the repository. Downgrading to libomp-5, of which there was an associated -dev allowed me to compile.

So I'm now running your master branch and I have re-checked the issue I was having with the Direct IO writes of block devices and it's now working fine. Hopefully it was just a bug that has since been fixed in wxHexEdit and nothing to do with running libomp-8 instead of libomp-5
