### ISSUE TITLE
Doesn't compile [master, Ubuntu buster/sid, gcc 9.2.1]

### ISSUE THREAD

**Issue by ambitslix** [EUA/wxHexEditor#150]
make WXCONFIG=wx-config CPPFLAGS="-fPIC" OPTFLAGS="-O3 -march-native -fopenmp"
make: *** No rule to make target '-lgomp', needed by 'src/HexEditorGui.o'.  Stop.

make: same problem.

libgomp1 is installed as well as openmp.

**Comment by EUA** [comment]
If its installed properly, why compiler cannot find the -lgomp?
I don't know but this sounds like a package error at your distro.
Please remove -fopenmp and -lgomp from make file and re-try.
wxHexEditor also work good without OpenMP.

**Comment by EUA** [comment]
I believe your compiler has no OpenMP support.
Please disable OpenMP by removing -lgomp line at Makefile.
Closing...

**Comment by lal12** [comment]
I have the same issue. I am by far not a make expert, but I am pretty sure that this is an issue in the makefile. 
`$(LIBS)` and therefore also `-lgomp` are made a target in line 53 (and ln 60). But make does not know about system libraries, so it assumes "-lgomp" is something it needs to built. So $(LIBS) needs to be split in STATIC_LIBS and DYN_LIBS or you could add an empty rule for "-lgomp".

**Comment by xdevelnet** [comment]
I have the same issue, even if:

1. Just make, no openmp installed
2. Just make, with openmp installed

Removing LIBS += -lgomp just solves the issue

**Comment by jackspsyc** [comment]
> 
gracias
