### ISSUE TITLE
udis86/scripts/ud_opcode.py

### ISSUE THREAD

**Issue by banditos13** [EUA/wxHexEditor#16]
in file udis86/scripts/ud_opcode.py for FC23 nedd add line at begin:
from __future__ import print_function
for construction: print(("%s   |-<%s>" % ( pfxs, idx )), end="", flush=True)
(Python 2.7.1)

**Comment by EUA** [comment]
Dropped local udis copy and using github repo as submodule at 52dbcbb5e44f88cd974ec36b450d188bb17ee03d
Thanks.

**Comment by EUA** [comment]
Original repo has some problems will revert this soon.

**Comment by EUA** [comment]
Fixed in 5b9460bcd280b91454822b1dec3f1634c2bc898f
At least compiles good on arch python 2.7 & 3.5
