### ISSUE TITLE
TAG Import not working on MacOS

### ISSUE THREAD

**Issue by EUA** [EUA/wxHexEditor#161]
This one from https://sourceforge.net/p/wxhexeditor/support-requests/12/
User takes "TAGS cannot be imported from <filepath>"
Will be check if it's true for latest version...

**Comment by Grotox** [comment]
Hi, I sent a tag file to my students using MacOS. Here is the file and a printscreen of the error generated.
[BMP.tags.txt](https://github.com/EUA/wxHexEditor/files/4580067/BMP.tags.txt)
<img width="1680" alt="BMP tags_error" src="https://user-images.githubusercontent.com/30216250/81054968-0cf1d480-8ec8-11ea-974e-ee240dcbfb21.png">

**Comment by EUA** [comment]
I can verify that, latest trunk does NOT have a this bug.
You can try to build from github trunk.
I also found another bug related with TAG showing mechanism, when trying to show tags, there are will be some problems... I remember this issue from past... Will fix it also.

**Comment by Grotox** [comment]
Thank you. 
And sorry but indeed, I don't know how to "build from github trunk sources" on Mac. If you could send a binary, I'd send it directly to my students for them to test it.

**Comment by EUA** [comment]
Hey, I don't forget it.
There are a popup window bug that avoids using clang compiler due wxHexEditor give segmentation fault with it.
Solution is compiling wxWidgets with gcc but I can't compile it with gcc with Catalina SDK.

So I have to debug code for clang on OSX first. Now, done. I have to make a quick bug check for OSX. Than will compile static wxWidgets library and the program last.
But... really busy this days.  Probably will compile and send ... when I wake up. (12:50pm here. Not sleep yet.)

**Comment by Grotox** [comment]
Wow, I'm really grateful for this job you're doing. Thanks a lot.
