### ISSUE TITLE
Text Search doesn't work

### ISSUE THREAD

**Issue by soba21** [EUA/wxHexEditor#166]
Hi,

In the search dialog the text search by use of "find all" works fine but when I use the button "search" it finds words that I didn't searched for! Or it shows me the wrong position, I don't know. Did anyone else had this problem?

Best regards
Soba

**Comment by EUA** [comment]
Version? Do you tried git trunk? Thanks.

**Comment by Bugfollower** [comment]
Hi,
Version 0.24 Beta.
Searching in a jpeg file for year "2021" in Exif metadata, to change time. "2021" is present 4 times in my file.
First search: finds the first place, but shows it one byte left.
In case of replacing, occurs on the wrong place, still one byte left.
Next search does not work at all.

**Comment by Alzigopri** [comment]
Hi,
here is the fix - https://github.com/EUA/wxHexEditor/pull/188

**Comment by EUA** [comment]
I merged the @Alzigopri's commit. Probably fixed now.
