### ISSUE TITLE
wxHexEditor not listed in 'All Applications"

### ISSUE THREAD

**Issue by sclaes** [EUA/wxHexEditor#167]
I can't open any file with wxHexEditor by clicking on the file. Is this a feature? ;-)

ATM I'm using Ubuntu but AFAIR I had the same problem with any Linux distro. (a.o. Linux Mint)
uname -a
Linux tau 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

wxEditor is not listed in the list of applications:
When I right-click on a file and  choose 'Open With Other Application' and then 'View All Applications', wxHexEditor should appear in the list but it doesn't (ghex IS listed).

Any idea why? Any suggestions?
TIA
S. Claes

**Comment by sclaes** [comment]
I solved the problem by editing /usr/share/applications/wxHexEditor.desktop.
I changed "Exec=wxHexEditor" to  "Exec=wxHexEditor %F".

BTW: Is there any reason why this is not the default?

**Comment by EUA** [comment]
Reason is; No one teaches me about how to create .desktop files. I believe that I just use some template and that template doesn't have it.
