### ISSUE TITLE
typos in code

### ISSUE THREAD

**Issue by mtrz** [EUA/wxHexEditor#169]
found some typos:

Enought --> Enough
https://github.com/EUA/wxHexEditor/blob/c22ce201034fd5554e6a5291611bcdc55eb2b8fc/src/FAL.cpp#L504
https://github.com/EUA/wxHexEditor/blob/c22ce201034fd5554e6a5291611bcdc55eb2b8fc/src/FAL.cpp#L514
https://github.com/EUA/wxHexEditor/blob/c22ce201034fd5554e6a5291611bcdc55eb2b8fc/src/FAL.cpp#L524

permissons --> permissions
https://github.com/EUA/wxHexEditor/blob/c22ce201034fd5554e6a5291611bcdc55eb2b8fc/src/FAL.cpp#L245
https://github.com/EUA/wxHexEditor/blob/c22ce201034fd5554e6a5291611bcdc55eb2b8fc/src/FAL.cpp#L284
https://github.com/EUA/wxHexEditor/blob/c22ce201034fd5554e6a5291611bcdc55eb2b8fc/src/FAL.cpp#L245

**Comment by markasoftware** [comment]
A more serious one is that "Options" was replaced with "asa" in eb10dbacb4f3bbe25b4735eac8b79914978568d6

**Comment by EUA** [comment]
Fixed all. Thanks for pointing out.
