### ISSUE TITLE
performance is poor

### ISSUE THREAD

**Issue by Eddi-z** [EUA/wxHexEditor#171]
I use wxHexEditor in OpenSUSE, and i tried the 0.24 from the default repository, and a self-compiled 0.25

performance is very poor after running the program a few seconds, even if no file is loaded. and `top` shows almost permanently a usage of 100% CPU (=1 single core)

**Comment by EUA** [comment]
I don't have this behaviour on my Arch. At least current trunk. Also I can't guess why such a behaviour appear on your computer.

**Comment by EUA** [comment]
Probably that fixed the issue. Closing this.
