### ISSUE TITLE
I have free disk space, but I still get a message that there is not enough disk space

### ISSUE THREAD

**Issue by RealFoxes** [EUA/wxHexEditor#172]
![image](https://user-images.githubusercontent.com/45780938/96348039-00002080-10b7-11eb-982d-cbb833ebc3c1.png)

**Comment by EUA** [comment]
I believe that this is not true for git trunk. Want to check it before release final v0.25

**Comment by EUA** [comment]
Yup fixed it before.
https://github.com/EUA/wxHexEditor/issues/98
