### ISSUE TITLE
wrong assignment

### ISSUE THREAD

**Issue by maddin200** [EUA/wxHexEditor#174]
[D:/Data/OpenSource/wxHexEditor-master/src/FAL.cpp line345:

		}
		waitpid(ProcessID, NULL, WUNTRACED);
		BlockRWSize=4;
		FAM == ReadOnly; // <- no assignment
		return true;
		}

**Comment by EUA** [comment]
Yeah, You catch it. I think it's on OSX.  Fixed on local.
