### ISSUE TITLE
The website is just a large image, no download links, pages, etc.

### ISSUE THREAD

**Issue by webdevterri** [EUA/wxHexEditor#178]
I went to the URL in the readme file to download an .exe but saw the website was just a large image with two lines of text that read: 

> SamyGO Networks
> infolink server building %90...

Is this website no longer in use for this project?

**Comment by kmpm** [comment]
Still the same.

**Comment by EUA** [comment]
Fixed. Yeah I just busy with crypto currencies... Returning back now. Thanks.
