### ISSUE TITLE
Does not notice when running out of space

### ISSUE THREAD

**Issue by Soukyuu** [EUA/wxHexEditor#18]
Following situation: 
- I have a 6GB /tmp with a 4.4GB .iso file in it
- I edit said file with wxHexEditor
- I save the file as a copy to /tmp
- wxHexEditor shows the progress and reaches 100% without any messages
-> the resulting file is only ~1.5GB in size

using current git snapshot via the archilinux x64 aur package.

**Comment by Soukyuu** [comment]
The issue is even weirder. After deleting the incomplete file, df still says there is 0 bytes free in /tmp
Removing the original .iso file doesn't free the space either. Shutting down wxHexEditor solves the issue. Looks like it keeps writing something to the disk, and writing much more than the 4.4GB it was supposed to write.

**Comment by EUA** [comment]
Now wxWidgets properly detect save issues and also checks free disk space before starting to save... 
c58a7d4a873b1c753bd34d69dfbcece702b66bf4
