### ISSUE TITLE
Duplicate praying code in a couple different languages

### ISSUE THREAD

**Issue by ungarson** [EUA/wxHexEditor#181]
Hi, I think we need to duplicate the praying code in at least 10 different languages, because I'm not sure if the God knows the English language.
https://github.com/EUA/wxHexEditor/blob/c22ce201034fd5554e6a5291611bcdc55eb2b8fc/src/HexEditor.cpp#L49

Also, I suggest trying binary format.

**Comment by litashg** [comment]
Hail the Omnissiah! He is the God in the Machine, the Source of All Knowledge.

**Comment by alygin** [comment]
I think the prayer language should depend on the current user locale. Or just make it configurable.

**Comment by ungarson** [comment]
No feedback. Closed.
