### ISSUE TITLE
File diff not finding all differences

### ISSUE THREAD

**Issue by luziferius** [EUA/wxHexEditor#190]
# Background

I’m currently reverse engineering a binary save file of a CarBest TV, in order to write a channel list editor. For that, I dump the list, perform some edit on the TV, then dump again and compare the files for changes using the _Compare Files_ option in the Tools menu. By pure chance, I noticed a changed byte that is _not_ highlighted by the diff logic and _not_ shown in the diff result view.

# Versions affected:

- Package 0.24 Beta as shipped in Ubuntu repositories
- Current master branch as of commit c22ce201034fd5554e6a5291611bcdc55eb2b8fc

# Screenshot:

The screenshot shows the location not identified: Offset 163524  
Highlighting mode is “Show differences”  
It also shows highlighting beyond the position to show that the option "Stop comparisons after X hits” is not active/causing this.

![Screenshot_20220313_143957](https://user-images.githubusercontent.com/2143820/158062367-40e8280d-cce3-49a8-8b03-757af6974feb.png)

# Affected files:

Attached are the two files shown in the screenshot, but packed as a GZip, in order to share them here.

[file1.bin.gz](https://github.com/EUA/wxHexEditor/files/8239600/file1.bin.gz)
[file2.bin.gz](https://github.com/EUA/wxHexEditor/files/8239601/file2.bin.gz)

**Comment by 18107** [comment]
I have been able to duplicate the issue with simpler files.

Unfound differences are at 112, 144, 176, 592, 624, 656, and 688. Interestingly, the difference at 80 was found.

![image](https://user-images.githubusercontent.com/7885724/210555604-6e28d0e1-a4a8-48c3-8707-d2452eedba42.png)

[button in.block.zip](https://github.com/EUA/wxHexEditor/files/10344050/button.in.block.zip)

[button out.block.zip](https://github.com/EUA/wxHexEditor/files/10344054/button.out.block.zip)

**Comment by EUA** [comment]
True. Thank you for indicating this bug. Will fix it.

**Comment by EUA** [comment]
> I have been able to duplicate the issue with simpler files.
> 
> Unfound differences are at 112, 144, 176, 592, 624, 656, and 688. Interestingly, the difference at 80 was found.

It's because of program compare buffers as integers, for speeding up. Not necessary indeed with speed of current CPUs but... It's free improvement.

When one diff found (at 80 in your scenario), it try to continue as integers by divide buffer location with i/4 bytes.
integer_buffer[81/4] and add 4 until another diff is found. But due rounding, skips some 4 bytes and this leads the bug.

I allow this speed up only if i is multiple of 4, and now it works as intended...
