### ISSUE TITLE
Button for file reload

### ISSUE THREAD

**Issue by nikita-yfh** [EUA/wxHexEditor#191]
I work with binary files of various programs, and I have to reload the file every time the file is changed in the program. It would be nice to add a button to reload a file from disk.

**Comment by EUA** [comment]
Doesn't it detect and reload automatically? I believe that I make it before. Might be disabled or... your OS is not supported by wxWidgets. I don't know but it should automatically reload file if detects any change on it.

**Comment by nikita-yfh** [comment]
Now the file is being reloaded automatically. By the time of my issue, file had not been reloaded automatically

**Comment by EUA** [comment]
Might be related with wxWidgets library. They add that feature optionally first than enable for other osses... Since there are no issue now, will close the issue :+1: 
thanks.
