### ISSUE TITLE
Offset in status bar does not update immediately after page down key

### ISSUE THREAD

**Issue by markasoftware** [EUA/wxHexEditor#192]
It switches to the wrong value, have to press another arrow key before it goes to the correct offset.

**Comment by markasoftware** [comment]
Actually, it's even worse. Try this:

1. Hold shift.
2. Press page down.
3. Press up arrow
4. Press down arrow
5. Look at the offset
6. Press up arrow

When you press the up arrow at the end, the offset actually _increases_!

**Comment by EUA** [comment]
I think this is duplicate of https://github.com/EUA/wxHexEditor/issues/204
Can you check it. I fixed some selection related code and I think this one is also fixed,

**Comment by markasoftware** [comment]
It seems like the issue is resolved on master!

I will note that there seems to be other weird stuff going on in the latest version -- it complains about the "Konkani" language not existing on my system when I start wxHexEditor, and there's also an unlabeled field between the 32-bit and 64-bit integer fields:

![Screenshot_20231021_143549](https://github.com/EUA/wxHexEditor/assets/6380084/383225c5-bd63-42be-a99a-3262e865b038)

**Comment by EUA** [comment]
Really weird. Everything looks proper here. Never heard anything about Konkani language. I tried on MacOSX and Linux... Not tried M$ version, yet...
