### ISSUE TITLE
Download links

### ISSUE THREAD

**Issue by AzazelHD** [EUA/wxHexEditor#200]
Sorry, im a bit lost on your main web page. Where can i download this tool for 64 bit windows?

**Comment by schrmh** [comment]
Navigation:
http://www.wxhexeditor.org/ "Enter Site"
http://www.wxhexeditor.org/home.php "Download"
http://www.wxhexeditor.org/download.php "Download wxHexEditor" (at the end of the site)
https://sourceforge.net/projects/wxhexeditor/ "Download" (green big button)

**Comment by AzazelHD** [comment]
Oh i see. I saw it but i was looking for a 64 bit version. I guess there isnt, right?

**Comment by schrmh** [comment]
https://sourceforge.net/projects/wxhexeditor/files/wxHexEditor/v0.24%20Beta/
