### ISSUE TITLE
Invalid selection block size

### ISSUE THREAD

**Issue by jakuup** [EUA/wxHexEditor#204]
Version: 0.24 Beta for Linux

Invalid value of "Block Size: XX" is displayed in the status panel when Up/Down or Home/End keys are used to select a block.
"Selected Block: AA -> BB" is also invalid in such case.
Seems to work correctly if Left/Right keys are used.

Example:

Initial state:
![1](https://github.com/EUA/wxHexEditor/assets/49183746/7739edab-de20-4a69-b20b-cb168c0249c0)

After pressing Shift+End:
![2](https://github.com/EUA/wxHexEditor/assets/49183746/c8ca34dd-cd1d-45d6-aca7-c11584b368cf)

After pressing Shift+Down:
![3](https://github.com/EUA/wxHexEditor/assets/49183746/1c9d0b10-8a7c-41ee-88ef-39eff10edd92)

**Comment by EUA** [comment]
Fixed locally.
