### ISSUE TITLE
Cut off unecessary leading zeros in "Go to Offset" (Ctrl+G dialog)

### ISSUE THREAD

**Issue by schrmh** [EUA/wxHexEditor#206]
When I open a file and it shows six digits for offsets, I can't enter the offset with more than 6 digits even when the additional digits are 0 (if I do enter more, the editor jumps to the end instead of ignoring the leading zeros).
I know about documentation that has 8 digits for offsets since it was originally written for use with some other hex editor.
And it would be nice if not every value in there needed adjustment (especially considering that there might be hex editors that want 8 digits for offset for some reason).

**Comment by EUA** [comment]
Hello. I return back to wxHexEditor. Willing to fix issues like this. But I can't understand this clear.
Go to offset accepts more than 6 digits.

![Screenshot from 2023-10-20 02-16-46](https://github.com/EUA/wxHexEditor/assets/125917/68d0781e-ae50-4db0-853c-236643413d16)

Which version of your wxHexEditor, on which OS?

**Comment by schrmh** [comment]
Exactly the same version as visible. 0.25 Beta for Linux. From the AUR, to be specific.
But yeah, I can't reproduce it either at the moment but I had it several times.
Either it only happens sometimes or it was some occasional mistake by me (I usually use this hex editor when working with files that have a encrypted and a decrypted version and one is way shorter thus it would jump at the end for them when searching for documented values). Too bad I did not attach anything for that.

Maybe we should close this issue until me or somebody else has it and deliver some video proof.
