### ISSUE TITLE
keyboard shortcuts do not work

### ISSUE THREAD

**Issue by newsgrep** [EUA/wxHexEditor#21]
Tested with 0.23 and 0.24

**Comment by EUA** [comment]
Looks working for me, using Linux.
Please give more info.

**Comment by Missingmew** [comment]
Digging up this old issue because it is still relevant: using current master, keyboard shortcuts do not work for me on debian-unstable. The menu items additionally do not show the shortcut combos as "Ctrl+N" but just as "N". Language is set to german in case this might be the issue.
