### ISSUE TITLE
Disassembler Panel TextCtrl does not properly resize.

### ISSUE THREAD

**Issue by rs333** [EUA/wxHexEditor#23]
Disassembler wxTextCtrl m_dasmCtrl does not resize with the Disassembler panel.  This makes it essentially impossible to use.  While I'm new to wxWidgets, changing line `683` of `HexEditorGui.cpp` to be the following appears to fix the problem.

`mainSizer->Add( m_dasmCtrl, 1, wxALIGN_CENTER_HORIZONTAL| wxBOTTOM | wxRIGHT | wxLEFT | wxEXPAND, 5 );`

I am running Fedora fc22.x86_64 with version 2.8.12 of wxWidgets.
wxHexEditor version 0.24 Beta Development.

**Comment by EUA** [comment]
Fixed
