### ISSUE TITLE
Panel Title not changed after changing the language

### ISSUE THREAD

**Issue by uchan** [EUA/wxHexEditor#24]
Platform: Windows 7 x64
Version: 0.23 beta

Steps I used:
1.unzip wxHexEditor-v0.23-Win32.zip
2.run wxHexEditor, it will use system language (my case: simplified chinese), with some panel enabled
3.choose a different language (for exsample: english), then restart wxHexEditor
4.Most UI component changed into new language (english), except the title of panel (still simplified chinese)

Please confirm, thank you.

**Comment by EUA** [comment]
Hello,
Not test it under Win7,
But "panel names" for example "Comparison Results" does not translate into required language under linux. Visible always in English on my PC. I just not realized those before.
Now fixed them in repo eef89f5
I believe, your problem will be fixed with this.
Regards
