### ISSUE TITLE
Broken GUI

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#25]
1. wxHexEditor 0.24 Beta Development for Linux
2. 0.23+git20161226
3. https://bugzilla.opensuse.org/show_bug.cgi?id=1022460#c25
![wxhe_ugly_interface_2017-02-03_12-50-01](https://cloud.githubusercontent.com/assets/7167300/22590474/0e95279a-ea18-11e6-8e04-f1b15b74c937.png)

See left side.

**Comment by EUA** [comment]
Fixed in 943c9dac356c9d878230dcc194dbf3d029092f65
You need to delete ~/.wxHexEditor config file for effect.
Please check.
