### ISSUE TITLE
wxStaticBox has wrong parental relationship

### ISSUE THREAD

**Issue by jengelh** [EUA/wxHexEditor#26]
```
wxStaticBoxSizer* sbSizerSearchOptions;
	sbSizerSearchOptions = new wxStaticBoxSizer( new wxStaticBox( this, wxID_ANY, _("Options") ), wxVERTICAL );
	
	chkMatchCase = new wxCheckBox( this, wxID_ANY, _("Match Case"), wxDefaultPosition, wxDefaultSize, 0 );
```
In wxWidgets 2.9.1 and above, elements that are visually going inside the staticbox also need the staticbox, _*not*_ `this`, as parent:
```
auto sbSizerSearchOptions = new wxStaticBoxSizer(wxVERTICAL, this, _("Options"));
auto sb = sbSizerSearchOptions->GetStaticBox();
chkMatchCase = new wxCheckBox(sb, wxID_ANY, _("Match Case"), ...);
```

**Comment by EUA** [comment]
Hi,
As it writes at top of the file (src/wxHexEditorGui.cpp):
// C++ code generated with wxFormBuilder (version Mar  8 2013)
and
// PLEASE DO "NOT" EDIT THIS FILE!

So it's auto generated cpp file.
Might using latest git version of wxFormEditor could fix this.
