### ISSUE TITLE
'Can't seek on file descriptor (error: 22 Invalid argument)' on Find/FindAll

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#29]
Hello!

Subj
![virtualbox_42 2_09_02_2017_14_34_29_gnome](https://cloud.githubusercontent.com/assets/7167300/22784894/8e2e7b8e-eeda-11e6-8d7c-305262df9c81.png)

![real_machine_wxhe_on_pidgin_xfce](https://cloud.githubusercontent.com/assets/7167300/22784915/a524fa16-eeda-11e6-844c-3494cd3aa106.png)

**Comment by EUA** [comment]
Fixed in  403ddd9
