### ISSUE TITLE
Change repository link from homepage to this git repository

### ISSUE THREAD

**Issue by Jiehong** [EUA/wxHexEditor#3]
It seems that this github repository is more up to date than the svn from sourceforge.

Perhaps it would be better to link the repository here, than on sourceforge?

According to https://github.com/EUA/wxHexEditor/issues/2, you said it seems better to point to the svn for now, but why is that?

**Comment by neoh4x0r** [comment]
I believe he meant that is was better to use SF.net ticket tracking system instead of the issues tracker on github. (https://sourceforge.net/p/wxhexeditor/_list/tickets)

**Comment by EUA** [comment]
:+1: You right.
I was really like SF.net's free service.
I will use here for source. Just not feel ready to move issues to here.

**Comment by EUA** [comment]
Done
