### ISSUE TITLE
Problem on switching items in search-list

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#30]
Hello!

1. Search-list contains two items (in hex): 7F454C46 (ELF e_ident) and 4D5A (MZ-PE e_magic).
2. Open some test ELF-file.
3. Push Find button, choose the second item and then push 'Find'.
4. wxHE finds 0 and item-list displays the first item from list.
5. Push Find again, item-list will be switched on second item and so on.

Something like: https://www.youtube.com/watch?v=b9TUfqBCHws

**Comment by EUA** [comment]
This is fixed.
