### ISSUE TITLE
To add $PID in 'Process cannot open' error message

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#31]
Hello!

Example: 'Open Process RAM' -> put 1 -> 'Process cannot open'

![2017-02-15_13-05-14](https://cloud.githubusercontent.com/assets/7167300/22971754/703a3c2c-f37f-11e6-9567-155dd6ec74c9.png)

Let us have: 'Process PID:$PID cannot be opened' as a more informative variant. Thanks!

**Comment by EUA** [comment]
Process PID?
I think "Process ID" is better :+1:
