### ISSUE TITLE
Lame Button on Device Image Tools Backup

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#32]
Hello!

Devices -> Device Image Tools -> Backup

![2017-02-15_13-07-27](https://cloud.githubusercontent.com/assets/7167300/22971874/f37a37fe-f37f-11e6-9e2d-68c3939e677b.png)

DE: XFCE 4.12

**Comment by EUA** [comment]
Those panels are replaced in GUI. For example button locations are switched.
Can you try with latest git?

Also why do you reference every issue with #27?
I do not understand an like it.

**Comment by EUA** [comment]
Fixed in 77bfce7

**Comment by MikhailKasimov** [comment]
It's not me , Git parses # combinations from backtraces as links on other bugs. Will attach backtraces as txt-file. Sorry for inconvenience.
