### ISSUE TITLE
The seach results panel displays 2 results for one found in "Find All"

### ISSUE THREAD

**Issue by plater** [EUA/wxHexEditor#41]
If you use Find All for a hex value that only exists once in a file two offsets are displayed in the search results panel. This is a minor cosmetic issue as both displayed offsets are true.

**Comment by plater** [comment]
Maybe related to issue#38

**Comment by MikhailKasimov** [comment]
There is a nuance.Take test-file from archive: https://bugzilla.suse.com/attachment.cgi?id=712598 (pass ti unpack: 111).

1) Put 4D5A search query. Result: you'll get 11 matches found (normally - 8). And, if you look carefully on 'Search Result' panel, you can notice, that first three matches have their duplication. See attach.
![2017-02-19_14-42-48](https://cloud.githubusercontent.com/assets/7167300/23102432/d7497a4c-f6b1-11e6-8185-786c172f4a3b.png)

**Comment by EUA** [comment]
Find algorithms are refactored recently. Will fix this out.

**Comment by EUA** [comment]
fixed in fa8e5a2
