### ISSUE TITLE
'Check file on VirusTotal' option enhancement-request

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#42]
Hello!

It seems to be an interesting idea to check file-status on VirusTotal ( [1] https://www.virustotal.com/) directly from wxH. E.g. 'Tools' -> 'Check on VirusTotal'. Of course, this is suitable only if network connection is on.

VT provides public API for such functionality:

[2] https://www.virustotal.com/en/documentation/public-api/

In particular - 'Retrieving file scan reports' paragraph: [3] https://www.virustotal.com/en/documentation/public-api/#getting-file-scans

**Comment by EUA** [comment]
Well, this does not fit to a HexEditor requirements I think.
For such a special request, It's better to implement "plugin" system.
So everyone could push it's plugin easy to do custom tasks.
Than it's easier to develop such plugins outside of the main program.
So this requirement does not gonna implemented at least by me.
