### ISSUE TITLE
wxHexeditor no longer builds for 32 bit intel

### ISSUE THREAD

**Issue by plater** [EUA/wxHexEditor#45]
Not sure what to do to correct this, occurs in the '#else' from '#ifdef __SSE2__' at src/HexDialogs.cpp:1346 I've only an x86_64 machine and attempts at compiling with -m32 bring up other errors. Seems like "i" needs a different type or something my c++ is poor.
Section from build log:
[   77s] src/HexDialogs.cpp:1459:6: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
[   77s]       if(! memcmp( bfr+i, search, search_size )) //if match found
[   77s]       ^~
[   77s] src/HexDialogs.cpp:1459:23: error: 'i' was not declared in this scope
[   77s]       if(! memcmp( bfr+i, search, search_size )) //if match found
[   77s]                        ^
[   77s] src/HexDialogs.cpp:1459:8: warning: suggest explicit braces to avoid ambiguous 'else' [-Wparentheses]
[   77s]       if(! memcmp( bfr+i, search, search_size )) //if match found
[   77s]         ^
[   77s] src/HexDialogs.cpp:1468:5: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
[   77s]      if( bfr[i] == search[0] || bfr[i] == UTF8SpeedHackChrs[0] )
[   77s]      ^~
[   77s] src/HexDialogs.cpp:1472:6: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'if'
[   77s]       if(! memcmp( bfr+i, search, search_size )) //if match found
[   77s]       ^~
[   77s] src/HexDialogs.cpp:1472:23: error: 'i' was not declared in this scope
[   77s]       if(! memcmp( bfr+i, search, search_size )) //if match found

Full log at:
https://build.opensuse.org/build/home:plater/openSUSE_Factory/i586/wxhexeditor/_log

I need to fix this before I can send the fixed wxhexeditor to openSUSE:Tumbleweed. Any suggestions welcome.

**Comment by EUA** [comment]
Hi Dave,
Thank you for report this.
Recently I implemented SSE2 enabled search routines and just push the code without testing with non-SSE2 environment.
Fixed now. baeeb58

**Comment by plater** [comment]
Finally fixed in rev#6aba1e26f3b6ed3d1c89b49bdf18c420d759bf33
