### ISSUE TITLE
Broken search-results on 'Find' and 'Search backward' option OFF [wxH: 0.23+git20170221-36.1]

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#46]
Hello!

wxH: 0.23+git20170221-36.1 in use.

Step-to-reproduce algo:

1) Open plain-text file.
2) Call search query window. Option: hex, other options are off.
3) Put hex-query, which will guaranteed give 'Not found' result, for example: 4D5A (**two bytes**).
4) Push 'Find'. Result: wxH will mark the **first two** bytes.
5) Push 'Find All'. wxH will return 'Search value not found' message window, and this is correct.
6) Switch on 'Search backward' option **ON** and push 'Find'. Result: 'Search value not found' message window, and this is correct.
7) Switch on 'Search backward' option **OFF** back, put 7F454C46 query (**four bytes**) and push 'Find'. Result: wxH will mark the **first four** bytes.
8) Push 'Find All'. wxH will return 'Search value not found' message window, and this is correct.
9) Switch on 'Search backward' option **ON** and push 'Find'. Result: 'Search value not found' message window, and this is correct.

Note: in case of Disassembler Panel is ON, execution of 'Find' with 'Search backward' is OFF will return '**invalid**' status.

Test file is attached: [test.txt](https://github.com/EUA/wxHexEditor/files/795154/test.txt)

P.S. And, traditionally, long story short: https://www.youtube.com/watch?v=lSTq6gDUSEw

**Comment by EUA** [comment]
Thanks,
Fixed in 6c515dc
Please re-check.

**Comment by MikhailKasimov** [comment]
> Please re-check.

UTR for 0.23+git20170223-44.1. Fixed. Thanks!
