### ISSUE TITLE
Broken search-results on zero-byte offset for text-mode searching. [wxH: 0.23+git20170221-36.1]

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#47]
Hello!

While waiting for wxH build with fix from #46, have tried the similar algo for text-mode.
Disassembler Panel in on.

Test file is the same from #46.

Steps-to-reproduce algo for 'Find' button:

1. Open test-file wxH.
2. Push Find.
3. Switch on ```Text``` mode. Other options are OFF.
4. Put single ``` = ``` sign as a search query and push 'Find' button. Result: wxH will mark the first byte offset, not null offset. **And this is the first bug**.
5. Do not close search-window and continue to push 'Find' button. After wxH gets the last ```=``` sign, it will switch on null-offset byte successfully. And this is correct.

Steps-to-reproduce algo for 'Find All' button:
1. Open test-file wxH.
2. Push Find.
3. Switch on ```Text``` mode. Other options are OFF.
4. Put single ``` = ``` sign as a search query and push 'Find All' button. Result: 48 matches will be found from the null-offset. So null-offset is not missed here instead of steps-to-reproduce algo for 'Find' button. But 48 matches result is wrong, because there are 24 (48/2) matches in real. This reminds #41 . **This is the second bug**. 

And in Disassembler panel you will get **invalid** status in.

Test-file is attached: [test.txt](https://github.com/EUA/wxHexEditor/files/796357/test.txt)

P.S. Long story short: https://www.youtube.com/watch?v=sOvd6pPc0WM

**Comment by MikhailKasimov** [comment]
For hex-mode (```3D``` search query) the problem is the same to text-mode, but 'Find all' gets 24 matches, and this is correct.

Resume:

- the first described bug is alive for both hex- and text-mode.
- the second described bug is alive for text-mode only.

**Comment by EUA** [comment]
Thank you for supplying the test.txt file.
First of all, when open a file, cursor start at offset 0.
And user **don't need** to find anything while cursor is already sitting on top of it.
So this is already expected situation.
"Search" made for **next** offsets. If you like to find about previous offsets (including current offset), you need to enable "wrap around" option.

File using "find" without "wrap around" option, pressing find does NOT jump back to zero offset as it in your video. Do no know why it behave on your setup.

FindAll just scan the file "twice" so results are duplicated. Just a cosmetic error. gonna fix this now.

**Comment by MikhailKasimov** [comment]
> So this is already expected situation.

ok, will know, thanks!

> FindAll just scan the file "twice" so results are duplicated. Just a cosmetic error. gonna fix this now.

Ok, thanks!

**Comment by EUA** [comment]
Added forgotten "else" clause to fix the issue 877f176.

**Comment by MikhailKasimov** [comment]
> File using "find" without "wrap around" option, pressing find does NOT jump back to zero offset as it in your video. On my computer, it does not get beck after last '=' character. Do no know why it behave on your setup.

wxH: 023+git20170224-50.1: https://www.youtube.com/watch?v=m3R7iJPm5S4 Funny thing. :)
