### ISSUE TITLE
wxString wxXmlNode::GetPropVal(const wxString&, const wxString&) const is deprecated

### ISSUE THREAD

**Issue by Jiehong** [EUA/wxHexEditor#5]
With WxWidget version > 2.8, `wxString wxXmlNode::GetPropVal(const wxString&, const wxString&) const` is now deprecated (https://github.com/wxWidgets/wxWidgets/blob/c7f1a920b1aeaa6760da4c99fd533ee01d5081b8/include/wx/xml/xml.h, line 179)

It is called in `src/HexEditorCtrl/HexEditorCtrl.cpp`.

It would be nice to fix this, so that it's ready for a higher wxwidget version.

**Comment by EUA** [comment]
Fixed in f7baf869c771654b8315dccb59790fb839a0fd75
