### ISSUE TITLE
SEGV 11 on Deleting some file-fragment

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#50]
Hello!

Version to reproduce: 0.23+git201702024-50.1

Test file: [123.txt](https://github.com/EUA/wxHexEditor/files/799225/123.txt)

BackTrace: [coredump_segv_11_023+git20170224-50.1_del.txt](https://github.com/EUA/wxHexEditor/files/799248/coredump_segv_11_023.git20170224-50.1_del.txt)

Steps-to-reproduce algo:

1. Open 123.txt in wxH.
2. Mark some fragment - to leave last eight bytes.
3. Right-click and Delete.
4. Mark these eight bytes again, right-click and choose 'Fill Selection'. I filled by FF instead of 00.
5. Mark FF-section you've got in 4., right-click and choose Delete.
6. After 5. is done, make single left-click on file area. Result: SEGV 11.

P.S. Visualization: https://www.youtube.com/watch?v=tvHBXOhDfnI

**Comment by EUA** [comment]
Hi @MikhailKasimov, You not need to indicate version numbers at _issue name_ like adding "[0.23+git201702024-50.1]", I don't like it. It's already included at body.
I will look this issue later.
Thanks.
