### ISSUE TITLE
Wrong block-size to delete after filling fragment

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#51]
Hello!

Version to reproduce: 0.23+git20170224-50.1

Test files: [test.txt](https://github.com/EUA/wxHexEditor/files/799659/test.txt) and [test_1.txt](https://github.com/EUA/wxHexEditor/files/799660/test_1.txt)

Steps-to-reproduce algo:

1. Open wxH.
2. Tools -> Compare Files. Choose test_1.txt and test.txt. All options are off by default.
Result: two files are opened and differences (absent fragment) are highlighted.
3. Select highlighted fragment and choose Delete. Result: deletion is normal, block-size is correct.
4. Revert changes from 3. back. Result: you'll get the highlighted fragment.
5. Select highlighted fragment and push 'Fill Selection' option. Fill will some symbols, e.g. CC.
6. Select filled fragment and push Delete. Result: wxH will delete block-size more, than it was defined by user.

Visualization: https://www.youtube.com/watch?v=Ce2Zw4Os8Jc

**Comment by EUA** [comment]
Hi,
Thank you for beta testing wxHexEditor.
I believe this issue is same as #50.
Also can I ask that, not open another issue report for "similar" issues?
For example #50 is related with delete, you can also put this req. under it since there are "problem with delete" even if appearances are different.
Regards.

**Comment by MikhailKasimov** [comment]
Hello!

> Also can I ask that, not open another issue report for "similar" issues?

To grade this "similarity" can developer only, who knows his own code, nuances etc. While wrong-size deletion didn't get segv-s, I've no reasons to suspect that segv in neighbor report has the same nature that the bug in current report.

So, I'll continue to put bugs-reports, questions, feature-requests as the dedicated reports. Regards.

**Comment by EUA** [comment]
1. Does this issue is fixed?
2. You can merge them if it related with "same function" ;)

Also while comparing two files, It's better to avoid insert/delete functions.
Thanks.

**Comment by MikhailKasimov** [comment]
1. Not yet, waiting for @plater 's help to get fresh build in suse repo.
2. In general way - yes, but when I can suspect the similarity of two bugs nature. ;)

> Also while comparing two files, It's better to avoid insert/delete functions.

Depends on what user wants here. For beta-tester, who tries to use the most twisted steps-to-reproduce algos to force program to crash, no. For others we can deactivate file-modifying functions (Cut, Fill Selection, Delete, Paste, Insert) in File-Compare mode by making them gray.

Do you wanna to see some street magic of dedicated issue for that? ;)

**Comment by plater** [comment]
@MikhailKasimov I can disconnect my wxhexeditor branch for you to use for testing if you wish and update it every morning.
I've updated to rev#30c88009b4e7e1df01b88721fc69f10e6cac6925
wxHexEditor-0.23+git20170226 is building:
https://build.opensuse.org/package/show/home:plater/wxhexeditor

**Comment by MikhailKasimov** [comment]
1. Fixed with wxHexEditor-0.23+git20170226. Block-size is ok on its deleting and no crashes on #50.

@plater Thanks for your help on building. I wish to have good utility, which works normally on its basic functionality.

**Comment by MikhailKasimov** [comment]
Fixed with wxHexEditor-0.23+git20170226
