### ISSUE TITLE
Unable to remove inotify watch on closing file

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#52]
Hello!

Version to reproduce: <= 0.23+git20170224-50.1

Very seldom, but anyway, I get this message-error, when I close wxH after viewing some file.

![2017-02-24_18-30-34](https://cloud.githubusercontent.com/assets/7167300/23311707/abbcc4d0-fabf-11e6-9dc8-5ff08e7d4633.png)

**Comment by MikhailKasimov** [comment]
Seems, this happens when file is opened by wxH and, after file is deleted from disk, user closes wxH. Don't even know if it is a bug -- on one hand wxH should prevent to delete opened file... So, there's needed developer's point of view.

**Comment by EUA** [comment]
It's related with FileWatcher mechanism.
wxHexEditor does not protect files when access it. Files are accessable with other programs.
If file changes, wxHexEditor detects the change and reload it. So you can see the difference.
But some programs (like gedit) does NOT modify the file but create new one and replace it with another one. In such situations, this error might be visible also due not predicted move. Will look on it but it's a cosmetic error, not something serious.

**Comment by MikhailKasimov** [comment]
Ok, thanks for clarifying.

**Comment by EUA** [comment]
I think this is old, fixed bug. Closing.
