### ISSUE TITLE
To extend 'Copy As' by Table -> CSV and Internet -> XML

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#53]
Hello!

There's an idea to to extend 'Copy As' [Ctrl-Shift-C] functionality by:

[New Paragraph of 'Copy As'] Table -> CSV
Internet -> XML [New option]

![2017-02-24_22-47-23](https://cloud.githubusercontent.com/assets/7167300/23320403/41764b40-fae3-11e6-9fac-7753dc945845.png)

Doable?

**Comment by EUA** [comment]
For CSV, you can use "Special Hex" -> "with 0x and period" generates
`0x66, 0x69, 0x6C, 0x65, 0x74,`

For Internet -> XML req, I have no idea about how represent HEX with XML form.
Even if there is a way to do that; do you have any idea about where to use it?

**Comment by MikhailKasimov** [comment]
> do you have any idea about where to use it?

Not yet in production-ready use-case. That was the common question. Ok, will close for now. In any time I can reopen it, if real use-cases become actual.

**Comment by MikhailKasimov** [comment]
Closed.

**Comment by EUA** [comment]
Also fixed "Special Hex" -> "with 0x and period", before it leave last ","
Indeed it's not period but "comma", will change it also.

**Comment by MikhailKasimov** [comment]
Suddenly -1 bug. :)
