### ISSUE TITLE
Pattern for filing new issues on wxH git

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#54]
Hello!

> You not need to indicate version numbers at issue name like adding "[0.23+git201702024-50.1]", I don't like it. It's already included at body. (see 50)

Ok, let this git has issue-filing pattern on pushing 'New issue' button. ;)

### Submission type

  - [x] Bug report
  - [x] Request for enhancement (RFE)
  - [x] Asking the question
 
### wxHexEditor version you use:

> …

### wxlib_ version you use:

> …

### Bug-report: describe your problem with wxH

> …

### Describe steps-to-reproduce algorithm of your problem with wxH

> …

### RFE: describe feature you wish to be added to wxH

> …

### Asking the question: put your question here

> …

**Comment by EUA** [comment]
I wasn't know if it even possible to do that in github. Thanks show me that.
Simply, I don't like it to have predefined or format for issues.
I believe formatted bug reports makes bug reporting stressful.
At least that's what I feel while reporting many bugs before.
Anyway I wish users could indicate their version and OS
