### ISSUE TITLE
SEGV on Tags Panel after deleting tag-marked file-fragment

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#55]
Hello!

Version to reproduce: 023+git20170226-1.1

've caught segv on Tags Panel navigation after deleting tag-marked file-fragment, but can't give you the normal steps-to-reproduce algo now.

My actions were: marking some file-fragments, filling sections, deleting tags-marked areas and then - trying to navigate on Tags Panel.

BackTrace: [segv_11_023+git20170226-1.1.txt](https://github.com/EUA/wxHexEditor/files/801932/segv_11_023.git20170226-1.1.txt)

**Comment by EUA** [comment]
I believe this is not related with Tag deletion ONLY. But deleted tags still lives on TagList.
I update Taglist after delete on new code.
Also fixed some other things (like interpeter panel).
Probably fixed now in 80af2583fb25f56a1503d9a16fe4a84e09dcdee5
