### ISSUE TITLE
SEGV on closing file-tabs

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#56]
Hello!

Version to reproduce: 023+git20170226-1.1

BackTrace: [segv_11_023+git20170226-1.1_on_closing_file-tabs.txt](https://github.com/EUA/wxHexEditor/files/802049/segv_11_023.git20170226-1.1_on_closing_file-tabs.txt)

**Comment by MikhailKasimov** [comment]
Another bt, but seems to be similar to initial: [segv_11_023+git20170226-1.1_on_deleting_block_from_new_file.txt](https://github.com/EUA/wxHexEditor/files/802067/segv_11_023.git20170226-1.1_on_deleting_block_from_new_file.txt)

**Comment by EUA** [comment]
Sorry, due no debugging symbols of the program at your debug log, I do not understand where is the problem. Please tell the steps that lead seg fault. Sorry.

**Comment by MikhailKasimov** [comment]
I was playing on block-sizes due to experiments I mentioned in 44. Cannot get the adequate constant algo of reproducing. And for debug-symbols I'll try again to get help from @plater.

Also will try to get normal steps-to-reproduce algo after taking a nap. Very tied, sorry...

**Comment by MikhailKasimov** [comment]
Steps-to-reproduce algo: https://www.youtube.com/watch?v=lzvVmdwtyw0

BT (sorry, without debuginfo). Seems this bt is similar to previous ones.
[segv_11_023+git20170226-1.1_on_deleting_block.txt](https://github.com/EUA/wxHexEditor/files/803111/segv_11_023.git20170226-1.1_on_deleting_block.txt)

**Comment by EUA** [comment]
Well, zero sized file is ... not a file at all in my perspective.
I do not know if wxHexEditor need to support zero length files at all...
But currently, it does NOT support. But just let users to make such operation (like deleting all file).
Might it's better to avoid this.
Do you have SEGV with 1byte files for example?

**Comment by MikhailKasimov** [comment]
> Do you have SEGV with 1byte files for example?

1byte is OK.

> Well, zero sized file is ... not a file at all in my perspective.
I do not know if wxHexEditor need to support zero length files at all...

In general way - not segv on them, when they are happened. :)

> But just let users to make such operation (like deleting all file).
Might it's better to avoid this.

Seems, the most simple way here is to restrict operations with 0-sized files.

**Comment by EUA** [comment]
It is easy to disable to remove operation that makes file 0 byte but what if user try to open a file which has zero byte?

**Comment by MikhailKasimov** [comment]
> but what if user try to open a file which has zero byte?

Let user to open it, but functions: ```Delete```, ```Cut```, ```Copy```, ```Copy As```, ```Save as Dump```, ```Find```, ```Find All```, ```Replace```, ```Go to Offset``` are to be inactive (gray).

**Comment by EUA** [comment]
Find/Find All/Replace operations are not needed to be disabled. Yes you cannot search on empty file but they will return no result. Let test it.

**Comment by MikhailKasimov** [comment]
Ok, will test. Thanks!

**Comment by plater** [comment]
wxhexeditor-0.23+git20170306 is now building, rev#425d17b1d0cadc037993a3d82d0652eac9c34f15

**Comment by MikhailKasimov** [comment]
Hello!

've tested at last on the last build: fixed.
