### ISSUE TITLE
To make new file size sign more obvious

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#57]
Hello!

![2017-02-26_19-53-44](https://cloud.githubusercontent.com/assets/7167300/23342159/1b25b3be-fc5e-11e6-9cb0-2cd2b3949c8e.png)

```Please indicate file size in decimal``` -> ```Please indicate file size (in bytes, 1 byte=8bits) in decimal```

BTW a question: Does wxH understand k|M|G suffixes for giving file size? E.g. 220 kB, 1MB, 100GB, etc?

**Comment by EUA** [comment]
Well, like k|M|G could be supported in future releases.

**Comment by EUA** [comment]
What do you think about IEC standards?
Some thinks that 1kB = 1000 and 1KB=1024.

**Comment by MikhailKasimov** [comment]
> What do you think about IEC standards?

Hello! 

```Because the SI prefixes strictly represent powers of 10, they should not be used to represent powers of 2. Thus, one kilobit, or 1 kbit, is 1000 bit and not 210 bit = 1024 bit. To alleviate this ambiguity, prefixes for binary multiples have been adopted by the International Electrotechnical Commission (IEC) for use in information technology.``` 

See https://physics.nist.gov/cuu/Units/prefixes.html)

Let's handle ```Prefixes for binary multiples``` -- https://physics.nist.gov/cuu/Units/binary.html

**Comment by EUA** [comment]
Yeah I know that but those scientist are from physics. Not from computer...
As I know, standard defines KB = 1024 and kB=1000 bytes (not bits).
But I think it's better to keep it 1024 for both for now. Because it's still ambiguous what to do with 10gB.
Anyway going to close this like that :)

**Comment by MikhailKasimov** [comment]
OK
