### ISSUE TITLE
Deactivating option file-modifying functions in File-Compare mode

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#59]
Hello!

> Also while comparing two files, It's better to avoid insert/delete functions

Deactivate file-modifying functions (Cut, Fill Selection, Delete, Paste, Insert) in File-Compare mode by making them gray.

Lets have it as a respective checkbox in option-list and it will be ```ON``` by default:

![2017-02-27_12-30-44](https://cloud.githubusercontent.com/assets/7167300/23357964/a7cb0514-fce8-11e6-86f2-eb389bea17cd.png)

**Comment by EUA** [comment]
Not all of them but related with insert/delete (includes cutting) operations are enough.
But "Paste" and "Fill Selections" does not alter files.
It's better to have them.
This might not update difference highlighted sections but It's OK I think.

**Comment by MikhailKasimov** [comment]
Ok, no problem on your idea.

**Comment by EUA** [comment]
Instead of adding checkbox, I think it's better to open files in "Read Only" mode.
User can switch it back to Writeable mode if required, later...
