### ISSUE TITLE
More informative offset-format on Tags Panel

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#62]
Hello!

Nowadays we have ```Offset:{start-offset}``` format on Tags Panel. E.g.:
![tags_panel_offset_values](https://cloud.githubusercontent.com/assets/7167300/23402090/cd3c9270-fdb2-11e6-8822-95bc4a665af0.png)

Seems to be convenient to have such format as being more informative:

```Offset {start-offset} - {end-offset}:{bytes}```.

For example:
1. ``` Offset 86``` -> ```Offset 86-101:16```
2. ``` Offset 293``` -> ```Offset 278-293:16```

BTW, here is (on 2.) a nuance, that wxH should consider such situation, when user marks his fragment to be tagged from right (start point to be tagged) to the left (end point to be tagged). So when offsets are to be counting down instead of counting up (from left to the right).

**Comment by EUA** [comment]
No problem, Code is already sort before creating tag.
Good enhancement.
Thanks.
