### ISSUE TITLE
Offset-counter field in DataInterpreter Panel

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#63]
Hello!

The idea is to have ```Offset:``` field in DataInterpreter Panel.

Yes, we can calculate our current offset position via offset rows and colons, but separate field --```Offset:``` field in DataInterpreter Panel -- of current offset position will be really appreciated to make user's life easier.

If it is already present, please open my eyes -- I can't see it anywhere in all panels, which are all switched on in ```View``` menu.

Thanks!

**Comment by EUA** [comment]
Hi,
Do you look at **status bar** at bottom, row 2? (or 1 if you start counting from 0)
It says cursor offset, not same thing with current offset if you select some block but. Don't know.
I do not close this now.
Might test it before reject.

**Comment by MikhailKasimov** [comment]
Indeed. Intuitively tried to find it on Data Panel...
