### ISSUE TITLE
Auto-tagging pasted fragments

### ISSUE THREAD

**Issue by MikhailKasimov** [EUA/wxHexEditor#64]
Hello!

>Auto tagging every pasted section might be another "feature".

Source: https://github.com/EUA/wxHexEditor/issues/44#issuecomment-282984913
This can be useful when pasting one or more big fragments. Tag Panel status: ```Pasted fragment. Offset {start-offset} - {end-offset}:{bytes}``` (see #62 for requested format).

>But then some users became unhappy due created tag files for nothing.

Let's have checkbox [x] in ```Options``` -> ```Preferences```. OFF by default.

**Comment by EUA** [comment]
I already said that similar and more natural way is on my checklist.
Not want to make over complicated options menu.
