### ISSUE TITLE
Unable to "Find Some Bytes" backward

### ISSUE THREAD

**Issue by CoruNethron** [EUA/wxHexEditor#69]
To reprosuce:
Open binary, that ends with some zero bytes. Select last byte. Open Search dialog, check "search backwards", try "Find Some Bytes".
Expected:
Found last non-zero byte.
Actual:
Cursor placed after last zero byte.

wxHexEditor 0.2.3 beta for Windows

**Comment by EUA** [comment]
It's because of not intended to use that button in backwards :)
Will implement it later. Might be for 0.25
