### ISSUE TITLE
Feature Request: CLI argument to open a file to a provided byte offset

### ISSUE THREAD

**Issue by chris-innanen** [EUA/wxHexEditor#70]
As a feature request that shouldn't be too hard to implement, it would be useful to be able to launch wxHexEditor from the command line and have it open to a given byte offset. For example:

    wxHexEditor  --offset 123456  input_file.bin

So that input_file.bin would be opened and scrolled to byte offset 123456 with the cursor placed there. Another optional addition would be to pass a byte selection length as well:

    wxHexEdotpr  --offset 123456  --selection 16  input_file.bin

Which would do the same as the above command but select 16 bytes starting with the offset byte.

Use case: If damage/corruption/error is detected in a custom file format, wxHexEditor can be launched as an external tool and told to display the offending portion of the data for investigation or repair.

**Comment by EUA** [comment]
What if 2 filename dropped? Which one opened in offset of 123456?
Selection might be specified better.
Let say --selection 123500+16

Currently parsing handed at:
`void wxHexEditorApp::MyAppInit()`

All of those require a better command line parser code to write. Might with help of wxCmdLineParser class

**Comment by EUA** [comment]
I work on it. Gonna support both --select 1000+10 & --select 1000:1010 notations.
