### ISSUE TITLE
udis86/

### ISSUE THREAD

**Issue by cstoribal** [EUA/wxHexEditor#73]
Hello !
I've read https://sourceforge.net/p/wxhexeditor/discussion/648351/thread/e79380f0/ as I got the same problem but on Ubuntu 16.04, but "make CC=gcc CXX=g++" didn't work and I didn't understand the answer given. I hope this problem is not a duplicate, I've not seen a more precise resolution of it. 
Thanks in advance !

**Comment by EUA** [comment]
Hi,
All you need to do is build udis86 first.
Don't know your environment.
do you tried
```
cd wxHexEditor/udis
./autogen.sh
./configure PYTHON=/usr/bin/python2
make
```
to build it? What is your error?
Regards
