### ISSUE TITLE
Disk corruption (wrong save offset)

### ISSUE THREAD

**Issue by LatinSuD** [EUA/wxHexEditor#77]
Hi, i was testing the 0.23 beta binary on Debian 8.

I was editing the MBR of a device (/dev/sdb).
When I click save it saved data at the wrong offset. After opening it again the sector seemed to be saved at offset 0x200.

**Comment by LatinSuD** [comment]
More details:
- When using Write mode it seems it won't save any data
- When using Direct Write mode it will write at the wrong offset

Also tried compiling the binary myself and it happened the same.

**Comment by EUA** [comment]
Really? What's gonna wrong this time?
Thanks for reporting. Will inspect and fix this ASAP.

**Comment by EUA** [comment]
After checking, it's not true for v0.24.
Please use git packages or compile it from source.
Regards.
