### ISSUE TITLE
Disable new version check by default (UpdateCheck=0)

### ISSUE THREAD

**Issue by thinrope** [EUA/wxHexEditor#78]
I just compiled/run wxHexEditor and was really surprised when it opened up a connection to the Internet...
(of course it was ran under supervision in restricted system, so that was detected).

Looking at [the code]( https://github.com/EUA/wxHexEditor/blob/11fee35f45bd22729e219db810d3a3462b8f69b0/src/HexEditorFrame.cpp#L193 ), it seems that on first run/per user it tries to connect to the Net and defaults to reconnecting every week.

I find this annoying for any type of application (there is OS package manager!), but especially for applications used for analysis of potential malware and/or not usually needing network access.

I think it can be disabled by having `UpdateCheck=0` in the (per user) config file, but please consider making this the default.

**Comment by EUA** [comment]
Default behavior is program checks if there are new version.
Since it's not harmful behavior and I also placed a disable option for this, this gonna stay / wont fix.

Also I don't want to implement a menu for put switch for that.
Sorry.
