### ISSUE TITLE
It should be possible to quickly throw out or forget all tags

### ISSUE THREAD

**Issue by petergeoghegan** [EUA/wxHexEditor#80]
Hi,

I've been using wxHexEditor for my work on Postgres for a while now, mostly with good results:

https://twitter.com/petervgeoghegan/status/881940573766144001

It would be nice if wxHedEditor proved to be a good basis for publishing a toolkit for reading the PostgreSQL block format.

I work from wxHedEditor's git tip directly, on Linux, but there is something that works against my current workflow: I cannot see a way to quickly throw out or forget the tags that I generate using my own custom program that generates wxHexEditor's XML format. wxHexEditor insists that it applies the same tags from the same tagfile as last time across restarts of wxHexEditor. That's not necessarily useful to me.

Similarly, I want to be able to generate new tags that supersede old tags with my external tool, since I may want to generate many tag files for the same file iteratively. For example, I sometimes start with generating a few tags for the more important stuff, to keep the memory overhead low. I may then decide that more detail is required, at which point I need to get rid of the less detailed tags to import the more detailed tags. Again, being able to quickly throw away tags before importing the new tagfile would be very useful.

Many thanks!

**Comment by EUA** [comment]
Well, you want a **tag clean** and **tag hide** options.
Looks OK to me on next v0.25

**Comment by petergeoghegan** [comment]
Thanks!

**Comment by petergeoghegan** [comment]
FYI, I have released my toolkit that handles creating tags + annotations for PostgreSQL relation files here: https://github.com/petergeoghegan/pg_hexedit

I do have a workaround for this issue, but it is quite ugly.

**Comment by EUA** [comment]
I need to develop a some generic scripting language or ruleset for parsing files automatically for bitmaps, jpegs, HDD MBRs...
It's super cool feature to have it.
I believe it's easy with python scripts... Yes it's not beautiful and fast as your C solution but It makes life easier to support new formats.

**Comment by petergeoghegan** [comment]
What I've done is certainly not the easiest way to get going. Though it does work well for me.

It would also be nice if the tags were collapsible. In other words, if tags could be nested. I'd definitely take advantage of it. I'd probably have each 8KiB block/page in a top-level tag, which contained various parts of the page, which finally contained the low-level tags that are actually rendered. Right now, I'm doing this hack with .wxHedEditor, to cache "interesting offsets" by making wxHexEditor think that they were previous user input. Whereas with nestable tags, users could just drill down to what they were looking for quickly, and there'd be no need for that hack at all.

Something to think about, perhaps.

Thanks

**Comment by EUA** [comment]
Since tags are designed to created by hand, some users could delete his/her all tags with a single button press is dangerous. Also there are no undo feature for tags. I believe we need some confirmation dialog for deletion of created tags.

Well, tag clean is implemented in 54435657667b4b19c938f1415bb0f07d6dd39653
Next is tag hide.

But collapsible tags that we need to think on it.
What about coloring of those tags?
What info appear on popup screen or secrens?
How much tags collapsible in same time... 
This definitely need to be handled alone in another request, not here...

**Comment by petergeoghegan** [comment]
@EUA This is great stuff. Thanks!

It would be particularly useful for my use-case if, in addition to the "Clear" and "Hide" buttons, there was also a new "Reload" button. This would be equivalent to pressing "Clear", and then re-importing the same tag file from the same location once again. It just saves time. (Potentially rather a lot of time, when the tags need to change to reflect changes that the user maxes as part of hex editing.)

**Comment by EUA** [comment]
Yup, It's useful for your case but not for general usage for wxHexEditor.
Only meaningful if there are auto tag generation / file template interpreter code implemented.
And I don't know how to implement such a feature yet but I already start to research on it.
