### ISSUE TITLE
Import templates

### ISSUE THREAD

**Issue by RuneN007** [EUA/wxHexEditor#84]
I think it would be nice with a menu File => Import TAGs. Using the tags xml (no change in it). I have a lot of templates for interpreting VBR, Attributes in NTFS MFT Record, etc... I can share them.

To create a template. Just save the selected area to a new file. The set the tags. Rename the autocreated tags file to .template and move the .template file it to a template folder. Then open a file goto the posisition where the structure starts, and import the template.  

The code to implement the insertion could be like this in the HexEditorFrame.cpp in the function OnMenuEvent:

```c++
case idImportTAGs:      {
    wxFileDialog filediag(this,_("Choose a file for import TAGs"), wxEmptyString, wxEmptyString, wxT("*.tags;*.template"), wxFD_OPEN|wxFD_CHANGE_DIR,  wxDefaultPosition); 

    if(wxID_OK == filediag.ShowModal()){
        #ifndef __WXMAC__
            if( !MyHexEditor->LoadTAGS( wxFileNameFromPath(filediag.GetPath()), MyHexEditor->CursorOffset() ) )
        #else
            if( !MyHexEditor->LoadTAGS( filediag.GetPath(), MyHexEditor->CursorOffset() ) )
        #endif
                wxMessageBox( wxString(_( "TAGS cannot be imported from ")).Append( filediag.GetPath() ),_("Error"), wxOK|wxICON_ERROR, this );
            else
                MyTagPanel->Set( MyHexEditor->MainTagArray );
            }
    break;

**Comment by RuneN007** [comment]
The picture below shows the dialog for selecting the template after File=> Import TAGs

<img width="1313" alt="selectingtemplate" src="https://user-images.githubusercontent.com/25431941/34078684-88bcde40-e31f-11e7-8367-1672c68a038e.png">

Then we see the hex view after inserting the ExFAT VBR template:
<img width="1173" alt="afterselection" src="https://user-images.githubusercontent.com/25431941/34078685-90b780f0-e31f-11e7-9349-babfb2b73b99.png">

**Comment by EUA** [comment]
Hi!
As I understand that, you want to **offset depended tag loading mechanism**.
Indeed I want to implement some template system, mentioned at #20 that also interpret files but this will take a time.
Until that time comes, your approach might be useful.

**Comment by RuneN007** [comment]
Hi,

Here you have some templates that you can play with

[Templates.tar.gz](https://github.com/EUA/wxHexEditor/files/1566018/Templates.tar.gz)

**Comment by EUA** [comment]
This brilliant solution awaits too much.
Now I get back to developing... Sorry for delay.
Only part that I don't like is ".template" extension, looks too generic to me.
Thanks for idea.

**Comment by RuneN007** [comment]
Hi, I am glad you liked the idea. Thank you for your contributions 😊

**Comment by EUA** [comment]
Can I add templates that you generated?

**Comment by RuneN007** [comment]
Yes, of course👍
