### ISSUE TITLE
0.24 ARM build fails

### ISSUE THREAD

**Issue by barjac** [EUA/wxHexEditor#90]
```
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp: In member function 'wxString wxHexTextCtrl::PrepareCodepageTable(wxString)':
src/HexEditorCtrl/wxHexCtrl/wxHexCtrl.cpp:2368:11: error: ambiguous overload for 'operator+=' (operand types are 'wxString' and 'unsigned int')
     newCP += ((i<0x20 || i==0x7F) ? '.' : wxChar(i));
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Building for Mageia armv7hl we get this error, the i586 and x86_64 builds are OK, albeit with lots of warnings.
I can provide full build log and all build chroot installed package versions if necessary.
Using wxgtk versions:
libwxgtku3.0-devel-3.0.3.1-2.mga7
libwxgtku3.0_0-3.0.3.1-2.mga7
libwxgtkugl3.0_0-3.0.3.1-2.mga7
wxgtk-3.0.3.1-2.mga7
Any ideas?

**Comment by EUA** [comment]
The error you faced is due your compiler instead of the dependencies.
Your compiler thinks characters as "unsigned int"
You need to change that line with

    newCP += ((i<0x20 || i==0x7F) ? wxString('.') : wxString(wxChar(i)));

This **probably** will solve your compiler issue. If not try this;
 
    if (i<0x20 || i==0x7F)
      newCP = newCP+wxString('.');
    else
      newCP = newCP+wxString(wxChar(i));

**Comment by barjac** [comment]
Thanks for your prompt reply - I will patch and test.

**Comment by barjac** [comment]
Yes, your first attempt did fix it - now builds OK in i586, x86_64 and armv7hl.
http://pkgsubmit.mageia.org/uploads/done/cauldron/core/release/20180103122451.barjac.duvel.29653/wxhexeditor-0.24-2.mga7/build.0.20180103122517.log
Will this change be committed in future releases?
Many thanks for your help,
Barry

**Comment by EUA** [comment]
Hi, I can commit the change into future release. Can you try this if it works?

    newCP += ((i<0x20 || i==0x7F)	? wxChar('.') : wxChar(i));

**Comment by barjac** [comment]
Yes that looks  OK too.
All arches built fine. :)

**Comment by EUA** [comment]
Thanks.
