### ISSUE TITLE
Please allow user to configure a font size larger than 32

### ISSUE THREAD

**Issue by AlisterH** [EUA/wxHexEditor#95]
Hi,
The wxhexeditor preferences dialog imposes a maximum font size of 32.  This is far too small in certain situations such as displaying on a TV, where dpi is much lower than a typical monitor.

Other software typically has a similar list of preset values (e.g. a maximum of 72 for GTK and 96 for libreoffice), but allows you to type in any number.

Thanks.

**Comment by EUA** [comment]
I make it 1-100. It could generate artifacts anyway.
