### ISSUE TITLE
your site   wxhexeditor.org  is offline

### ISSUE THREAD

**Issue by scottstensland** [EUA/wxHexEditor#97]
it just says

```
Project web is currently offline pending the final migration of its data to our new datacenter.
```

**Comment by EUA** [comment]
Yup.
It is sourceforge.
If they don't bring it up under week I move it to my private hosting.
Lazy about moving it. :)

**Comment by merces** [comment]
DId you consider Github Pages already?

**Comment by EUA** [comment]
I don't aware from Github "pages".
Just moved my site to new host instead of sourceforge servers.

**Comment by hardhub** [comment]
@EUA Now www.wxhexeditor.org shows strange content:

![image](https://user-images.githubusercontent.com/4306334/137202400-5d32aa8b-922b-4af9-96f4-74939f5b7d7e.png)

**Comment by EUA** [comment]
Oops. I don't expect such a thing... Virtual host has Apache cache error. Fixed now. Thanks.
