### ISSUE TITLE
wxHexEditor-v0.24 cannot "Save file as:"

### ISSUE THREAD

**Issue by davidbharper** [EUA/wxHexEditor#98]
After using XORView Thru on a .prf file and using the XOR key as Hex, 11, it is not possible to save the newly converted file as anything due to this error message:

Not Enough Space
There are not enough free disk space.
Required: 506.5 Kb
Available: Not Available

Not experiencing any problems with the older version-v0.20a.
I am using Windows 10 Pro 64-bit.  There are 142 Gb of free space available.  No other editing was performed on the file.  I simply opened the file, used XORView Thru and tried to save it as a renamed .prf file.

**Comment by EUA** [comment]
I tried under linux and it could save.
From error message, your disk area looks not available for write.
This probably free space detection issue.
Will investigate this further.

**Comment by davidbharper** [comment]
Hi Erdem.  Thanks for looking into this problem.   There are 142 Gb of free space available. No other editing was performed on the file. I simply opened the file, used XORView Thru and tried to save it as a renamed .prf file.  The original file's properties Size is 506 KB (518,679 bytes) and Size on disk:  508 KB (520,192 bytes).

**Comment by hedgehog90** [comment]
This is still an issue.
I can't save as any files in v0.24 windows version.

**Comment by GitHubIsToxic** [comment]
Same issue with latest beta build (0.24), on Windows 10, plenty free disk space. The file I'm trying to save is ~5 MB.

**Comment by EUA** [comment]
I probably fixed this after release. Please wait for next release soon. I will open it due test this.
You can try compile git version to check if it is working. Thanks.

**Comment by azn1viet** [comment]
still see the issue now with version 0.2.4 in Windows

**Comment by EUA** [comment]
Using latest trunk, I don't see such an issue.
I can send exe binaries who can't compile.
Thanks.

**Comment by rodneylives** [comment]
I am suffering from this issue as well, and don't have easy means to compile.

**Comment by EUA** [comment]
> I am suffering from this issue as well, and don't have easy means to compile.

As I said, I can send executable files of current trunk for windows, if you like. Thanks.

**Comment by rodneylives** [comment]
That would be much appreciated, but, how?

**Comment by EUA** [comment]
You can ask via e-mail?
Hey, couldn't I upload here, temporarily? :)

[wxHexEditor.zip](https://github.com/EUA/wxHexEditor/files/3964960/wxHexEditor.zip)

**Comment by rodneylives** [comment]
Ah, thanks! I'll post bugs if I find any more. I was a bit standoffish about posting my email address here, but eh, I doubt it'll mean I get even *more* spam.

**Comment by EUA** [comment]
PS: My mail is available at last line at Help->About->License :)

**Comment by rodneylives** [comment]
I downloaded it through your link (so you can take it down now if you like).

I could email you at that address, but how could you be sure it was me? Although I guess there's no reason someone else would want it, unless they were experiencing the same bug.

In any case, thanks very much!

**Comment by pauloasherring** [comment]
I had the same issue, version 0.25 corrected it! Thanks, @EUA !

**Comment by pcjc2** [comment]
Would there be any chance of binary release (including Windows 32bit) for version 0.25 please?
